# Generated by Django 3.2.4 on 2021-07-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("github_export", "0002_auto_20200411_2148"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookrepository",
            options={"verbose_name_plural": "Book repositories"},
        ),
    ]
