# Generated by Django 3.2.4 on 2021-09-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_export", "0003_alter_bookrepository_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookrepository",
            name="export_unified_html",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
