
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-17T15:32:46-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "5c23f01c984be3dc685eae5750ee227aff41d0e7",
 "version": "1.16.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
