
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-05T10:48:51+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a13ad667c62aaaff90a2be954a7d30ce35a6036d",
 "version": "0.4+13.ga13ad66"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
