
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-15T17:12:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f14581dc99f093363c6a2daf7afd677c272f1ab1",
 "version": "0.0.67"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
