
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-12T11:09:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f013e58381e906d1f49150f6af9605ae3e08d81c",
 "version": "2021.11.0+3.gf013e58"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
