"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc

from .retrieval_pb2 import *
class RetrievalServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    Retrieve:grpc.UnaryUnaryMultiCallable[
        global___RetrieveRequest,
        global___RetrieveResponse] = ...


class RetrievalServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Retrieve(self,
        request: global___RetrieveRequest,
        context: grpc.ServicerContext,
    ) -> global___RetrieveResponse: ...


def add_RetrievalServiceServicer_to_server(servicer: RetrievalServiceServicer, server: grpc.Server) -> None: ...
