VERSION_YEAR = 2021
VERSION_MONTH = int('11')
VERSION_DAY = int('12')
VERSION_HOUR = int('19')
VERSION_MINUTE = int('55')
MAJOR_VERSION = 1
MINOR_VERSION = 6
PATCH_VERSION = 202111121955
version_date = '2021/11/12 19:55'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
