[tool.poetry]
name = "autobright"
version = "0.1.0"
description = "Automatically adjust display brightness with external sensor"
authors = ["Martin Ueding <mu@martin-ueding.de>"]
license = "MIT"

[tool.poetry.scripts]
autobright = "autobright.__main__:main"

[tool.poetry.dependencies]
python = "^3.8"
streamlit = "^1.2.0"
altair = "^4.1.0"
pandas = "^1.3.4"
appdirs = "^1.4.4"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.10b0"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"