"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc

from .entailment_pb2 import *
class EntailmentServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    Entailment:grpc.UnaryUnaryMultiCallable[
        global___EntailmentRequest,
        global___EntailmentResponse] = ...

    Entailments:grpc.UnaryUnaryMultiCallable[
        global___EntailmentsRequest,
        global___EntailmentsResponse] = ...


class EntailmentServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Entailment(self,
        request: global___EntailmentRequest,
        context: grpc.ServicerContext,
    ) -> global___EntailmentResponse: ...

    @abc.abstractmethod
    def Entailments(self,
        request: global___EntailmentsRequest,
        context: grpc.ServicerContext,
    ) -> global___EntailmentsResponse: ...


def add_EntailmentServiceServicer_to_server(servicer: EntailmentServiceServicer, server: grpc.Server) -> None: ...
