# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['language_data']

package_data = \
{'': ['*'],
 'language_data': ['data/*',
                   'data/trie/af/*',
                   'data/trie/agq/*',
                   'data/trie/ak/*',
                   'data/trie/am/*',
                   'data/trie/ang/*',
                   'data/trie/ar/*',
                   'data/trie/as/*',
                   'data/trie/asa/*',
                   'data/trie/ast/*',
                   'data/trie/az/*',
                   'data/trie/bas/*',
                   'data/trie/be/*',
                   'data/trie/bem/*',
                   'data/trie/bez/*',
                   'data/trie/bg/*',
                   'data/trie/bho/*',
                   'data/trie/bm/*',
                   'data/trie/bn/*',
                   'data/trie/bo/*',
                   'data/trie/br/*',
                   'data/trie/brx/*',
                   'data/trie/bs/*',
                   'data/trie/ca/*',
                   'data/trie/ccp/*',
                   'data/trie/ce/*',
                   'data/trie/ceb/*',
                   'data/trie/cgg/*',
                   'data/trie/chr/*',
                   'data/trie/ckb/*',
                   'data/trie/cs/*',
                   'data/trie/cu/*',
                   'data/trie/cy/*',
                   'data/trie/da/*',
                   'data/trie/dav/*',
                   'data/trie/de/*',
                   'data/trie/dje/*',
                   'data/trie/doi/*',
                   'data/trie/dsb/*',
                   'data/trie/dua/*',
                   'data/trie/dyo/*',
                   'data/trie/dz/*',
                   'data/trie/ebu/*',
                   'data/trie/ee/*',
                   'data/trie/el/*',
                   'data/trie/en/*',
                   'data/trie/eo/*',
                   'data/trie/es/*',
                   'data/trie/et/*',
                   'data/trie/eu/*',
                   'data/trie/ewo/*',
                   'data/trie/fa/*',
                   'data/trie/ff/*',
                   'data/trie/fi/*',
                   'data/trie/fil/*',
                   'data/trie/fo/*',
                   'data/trie/fr/*',
                   'data/trie/fur/*',
                   'data/trie/fy/*',
                   'data/trie/ga/*',
                   'data/trie/gd/*',
                   'data/trie/gl/*',
                   'data/trie/gsw/*',
                   'data/trie/gu/*',
                   'data/trie/guz/*',
                   'data/trie/gv/*',
                   'data/trie/ha/*',
                   'data/trie/haw/*',
                   'data/trie/he/*',
                   'data/trie/hi/*',
                   'data/trie/hil/*',
                   'data/trie/hr/*',
                   'data/trie/hsb/*',
                   'data/trie/hu/*',
                   'data/trie/hy/*',
                   'data/trie/ia/*',
                   'data/trie/id/*',
                   'data/trie/ig/*',
                   'data/trie/ii/*',
                   'data/trie/ilo/*',
                   'data/trie/io/*',
                   'data/trie/is/*',
                   'data/trie/it/*',
                   'data/trie/ja/*',
                   'data/trie/jbo/*',
                   'data/trie/jgo/*',
                   'data/trie/jmc/*',
                   'data/trie/jv/*',
                   'data/trie/ka/*',
                   'data/trie/kab/*',
                   'data/trie/kam/*',
                   'data/trie/kcm/*',
                   'data/trie/kde/*',
                   'data/trie/kea/*',
                   'data/trie/kgp/*',
                   'data/trie/khq/*',
                   'data/trie/ki/*',
                   'data/trie/kk/*',
                   'data/trie/kkj/*',
                   'data/trie/kl/*',
                   'data/trie/kln/*',
                   'data/trie/km/*',
                   'data/trie/kn/*',
                   'data/trie/ko/*',
                   'data/trie/kok/*',
                   'data/trie/ks/*',
                   'data/trie/ksb/*',
                   'data/trie/ksf/*',
                   'data/trie/ksh/*',
                   'data/trie/ku/*',
                   'data/trie/kw/*',
                   'data/trie/ky/*',
                   'data/trie/la/*',
                   'data/trie/lag/*',
                   'data/trie/lah/*',
                   'data/trie/lb/*',
                   'data/trie/lg/*',
                   'data/trie/lkt/*',
                   'data/trie/ln/*',
                   'data/trie/lo/*',
                   'data/trie/lrc/*',
                   'data/trie/lt/*',
                   'data/trie/lu/*',
                   'data/trie/luo/*',
                   'data/trie/luy/*',
                   'data/trie/lv/*',
                   'data/trie/mai/*',
                   'data/trie/mas/*',
                   'data/trie/mer/*',
                   'data/trie/mfe/*',
                   'data/trie/mg/*',
                   'data/trie/mgh/*',
                   'data/trie/mgo/*',
                   'data/trie/mi/*',
                   'data/trie/mk/*',
                   'data/trie/ml/*',
                   'data/trie/mn/*',
                   'data/trie/mni/*',
                   'data/trie/mr/*',
                   'data/trie/ms/*',
                   'data/trie/mt/*',
                   'data/trie/mua/*',
                   'data/trie/my/*',
                   'data/trie/mzn/*',
                   'data/trie/nah/*',
                   'data/trie/nan/*',
                   'data/trie/naq/*',
                   'data/trie/nb/*',
                   'data/trie/nd/*',
                   'data/trie/nds/*',
                   'data/trie/ne/*',
                   'data/trie/nl/*',
                   'data/trie/nmg/*',
                   'data/trie/nn/*',
                   'data/trie/nnh/*',
                   'data/trie/no/*',
                   'data/trie/nus/*',
                   'data/trie/nv/*',
                   'data/trie/nyn/*',
                   'data/trie/om/*',
                   'data/trie/or/*',
                   'data/trie/os/*',
                   'data/trie/pa/*',
                   'data/trie/pcm/*',
                   'data/trie/pl/*',
                   'data/trie/prg/*',
                   'data/trie/ps/*',
                   'data/trie/pt/*',
                   'data/trie/qu/*',
                   'data/trie/rm/*',
                   'data/trie/rn/*',
                   'data/trie/ro/*',
                   'data/trie/rof/*',
                   'data/trie/ru/*',
                   'data/trie/rup/*',
                   'data/trie/rw/*',
                   'data/trie/rwk/*',
                   'data/trie/sa/*',
                   'data/trie/sah/*',
                   'data/trie/saq/*',
                   'data/trie/sat/*',
                   'data/trie/sbp/*',
                   'data/trie/sc/*',
                   'data/trie/sd/*',
                   'data/trie/se/*',
                   'data/trie/seh/*',
                   'data/trie/ses/*',
                   'data/trie/sg/*',
                   'data/trie/sh/*',
                   'data/trie/shi/*',
                   'data/trie/si/*',
                   'data/trie/sk/*',
                   'data/trie/sl/*',
                   'data/trie/smn/*',
                   'data/trie/sn/*',
                   'data/trie/so/*',
                   'data/trie/sq/*',
                   'data/trie/sr/*',
                   'data/trie/su/*',
                   'data/trie/sv/*',
                   'data/trie/sw/*',
                   'data/trie/ta/*',
                   'data/trie/te/*',
                   'data/trie/teo/*',
                   'data/trie/tg/*',
                   'data/trie/th/*',
                   'data/trie/ti/*',
                   'data/trie/tk/*',
                   'data/trie/to/*',
                   'data/trie/tpi/*',
                   'data/trie/tr/*',
                   'data/trie/tt/*',
                   'data/trie/twq/*',
                   'data/trie/tzm/*',
                   'data/trie/ug/*',
                   'data/trie/uk/*',
                   'data/trie/und/*',
                   'data/trie/ur/*',
                   'data/trie/uz/*',
                   'data/trie/vai/*',
                   'data/trie/ve/*',
                   'data/trie/vi/*',
                   'data/trie/vo/*',
                   'data/trie/vun/*',
                   'data/trie/wae/*',
                   'data/trie/wo/*',
                   'data/trie/xh/*',
                   'data/trie/xog/*',
                   'data/trie/yav/*',
                   'data/trie/yi/*',
                   'data/trie/yo/*',
                   'data/trie/yrl/*',
                   'data/trie/yue/*',
                   'data/trie/zgh/*',
                   'data/trie/zh/*',
                   'data/trie/zsm/*',
                   'data/trie/zu/*',
                   'data/wiktionary/*']}

install_requires = \
['marisa-trie>=0.7.7,<0.8.0']

setup_kwargs = {
    'name': 'language-data',
    'version': '1.1',
    'description': 'Supplementary data about languages used by the langcodes module',
    'long_description': '# language_data: a supplement to [langcodes][]\n\n[langcodes]: https://github.com/LuminosoInsight/langcodes\n\nThis package is not meant to be used on its own. Please see [langcodes][] for documentation.\n\n`language_data` is a supplement to the langcodes module, for working with standardized codes for human languages. It stores the more bulky and hard-to-index data about languages, particularly what they are named in various languages.\n\nFor example, this stores the data that tell you that the code "en" means "English" in English, or that "francés" is the Spanish (es) name for French (fr).\n\nThe functions and test cases for working with this data are in [langcodes][], because working with the data correctly requires parsing language codes.\n\n## Data\n\nThe data included in this package is:\n\n- The names of various languages, in various languages\n- The estimated population that speaks each language\n- The estimated population that writes each language\n\nThese are all extracted from the Unicode [CLDR][] data package, version 40, plus a few additional language names that fill in gaps in CLDR.\n\n[cldr]: http://cldr.unicode.org/\n\n## Caveats\n\n- The estimates for "writing population" are often overestimates, as described in the [CLDR documentation on territory data][overestimates]. In most cases, they are derived from published data about literacy rates in the places where those languages are spoken. This doesn\'t take into account that many literate people around the world speak a language that isn\'t typically written, and write in a _different_ language.\n\n- The writing systems of Chinese erase most (but not all) of the distinctions between spoken Chinese languages. You\'ll see separate estimates of the writing population for Cantonese, Mandarin, Wu, and so on, even though you\'ll likely consider these all to be `zh` when written.\n\n- CLDR doesn\'t have language population data for sign languages. Sign languages end up with a `speaking_population()` and `writing_population()` of 0, and I suppose that is literally true, but there\'s no data from which we could provide a `signing_population()` method.\n\n[overestimates]: https://unicode-org.github.io/cldr-staging/charts/38.1/supplemental/territory_language_information.html\n\n## Dependencies\n\n`language_data` has a dependency on the `marisa-trie` package so that it can load a compact, efficient data structure for looking up language names.\n\n## Installation\n\n`language_data` is usually installed as a dependency of `langcodes`, and doesn\'t make much sense without it. You can `pip install language_data` anyway if you want.\n\nTo install the `language_data` package in editable mode, run `poetry install` in the package root. (This is the equivalent of `pip install -e .`, which currently doesn\'t work because pip does not yet fully support PEP 621.)\n',
    'author': 'Elia Robyn Speer',
    'author_email': 'rspeer@arborelia.net',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/rspeer/language_data',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.6',
}


setup(**setup_kwargs)
