# automatically generated by the FlatBuffers compiler, do not modify

# namespace: datalayer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Counting(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCounting(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Counting()
        x.Init(buf, n + offset)
        return x

    # Counting
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Counting
    def CountSubscriptions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def CountingStart(builder): builder.StartObject(1)
def CountingAddCountSubscriptions(builder, countSubscriptions): builder.PrependBoolSlot(0, countSubscriptions, 0)
def CountingEnd(builder): return builder.EndObject()
