# automatically generated by the FlatBuffers compiler, do not modify

# namespace: datalayer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Int8(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInt8(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Int8()
        x.Init(buf, n + offset)
        return x

    # Int8
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Int8
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def Int8Start(builder): builder.StartObject(1)
def Int8AddValue(builder, value): builder.PrependInt8Slot(0, value, 0)
def Int8End(builder): return builder.EndObject()
