# automatically generated by the FlatBuffers compiler, do not modify

# namespace: datalayer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ProgramTaskAll(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsProgramTaskAll(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProgramTaskAll()
        x.Init(buf, n + offset)
        return x

    # ProgramTaskAll
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProgramTaskAll
    def Tasks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from comm.datalayer.ProgramTask import ProgramTask
            obj = ProgramTask()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ProgramTaskAll
    def TasksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ProgramTaskAll
    def TasksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ProgramTaskAllStart(builder): builder.StartObject(1)
def ProgramTaskAllAddTasks(builder, Tasks): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(Tasks), 0)
def ProgramTaskAllStartTasksVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ProgramTaskAllEnd(builder): return builder.EndObject()
