# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db_crud.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='db_crud.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\013/crud_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rdb_crud.proto\"_\n\x08\x41\x64\x64Param\x12\x11\n\tVideoName\x18\x01 \x01(\t\x12\x11\n\tVideoPath\x18\x02 \x01(\t\x12\x15\n\rVideoInfoPath\x18\x03 \x01(\t\x12\x16\n\x0eVideoTransPath\x18\x04 \x01(\t\"\x16\n\x06\x41\x64\x64Res\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x05\":\n\x08ModParam\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x05\x12\x0e\n\x06ModKey\x18\x02 \x01(\t\x12\x10\n\x08ModValue\x18\x03 \x01(\t\"\x19\n\x06ModRes\x12\x0f\n\x07ModData\x18\x01 \x01(\t\"\x18\n\x08\x44\x65lParam\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x05\"\x19\n\x06\x44\x65lRes\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\'\n\x08SelParam\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x05\x12\r\n\x05Video\x18\x02 \x01(\t\"!\n\x06SelRes\x12\x17\n\x06SelMap\x18\x01 \x03(\x0b\x32\x07.Result\"\\\n\x06Result\x12#\n\x06result\x18\x01 \x03(\x0b\x32\x13.Result.ResultEntry\x1a-\n\x0bResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x91\x01\n\x0b\x44\x61taService\x12\x1f\n\x07\x41\x64\x64\x44\x61ta\x12\t.AddParam\x1a\x07.AddRes\"\x00\x12\x1f\n\x07ModData\x12\t.ModParam\x1a\x07.ModRes\"\x00\x12\x1f\n\x07\x44\x65lData\x12\t.DelParam\x1a\x07.DelRes\"\x00\x12\x1f\n\x07SelData\x12\t.SelParam\x1a\x07.SelRes\"\x00\x42\rZ\x0b/crud_protob\x06proto3'
)




_ADDPARAM = _descriptor.Descriptor(
  name='AddParam',
  full_name='AddParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='VideoName', full_name='AddParam.VideoName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='VideoPath', full_name='AddParam.VideoPath', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='VideoInfoPath', full_name='AddParam.VideoInfoPath', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='VideoTransPath', full_name='AddParam.VideoTransPath', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=112,
)


_ADDRES = _descriptor.Descriptor(
  name='AddRes',
  full_name='AddRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='AddRes.flag', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=136,
)


_MODPARAM = _descriptor.Descriptor(
  name='ModParam',
  full_name='ModParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='ModParam.flag', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ModKey', full_name='ModParam.ModKey', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ModValue', full_name='ModParam.ModValue', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=196,
)


_MODRES = _descriptor.Descriptor(
  name='ModRes',
  full_name='ModRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ModData', full_name='ModRes.ModData', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=223,
)


_DELPARAM = _descriptor.Descriptor(
  name='DelParam',
  full_name='DelParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='DelParam.flag', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=249,
)


_DELRES = _descriptor.Descriptor(
  name='DelRes',
  full_name='DelRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='DelRes.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=276,
)


_SELPARAM = _descriptor.Descriptor(
  name='SelParam',
  full_name='SelParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='SelParam.flag', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Video', full_name='SelParam.Video', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=317,
)


_SELRES = _descriptor.Descriptor(
  name='SelRes',
  full_name='SelRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='SelMap', full_name='SelRes.SelMap', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=352,
)


_RESULT_RESULTENTRY = _descriptor.Descriptor(
  name='ResultEntry',
  full_name='Result.ResultEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Result.ResultEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Result.ResultEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=446,
)

_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='Result.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RESULT_RESULTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=446,
)

_SELRES.fields_by_name['SelMap'].message_type = _RESULT
_RESULT_RESULTENTRY.containing_type = _RESULT
_RESULT.fields_by_name['result'].message_type = _RESULT_RESULTENTRY
DESCRIPTOR.message_types_by_name['AddParam'] = _ADDPARAM
DESCRIPTOR.message_types_by_name['AddRes'] = _ADDRES
DESCRIPTOR.message_types_by_name['ModParam'] = _MODPARAM
DESCRIPTOR.message_types_by_name['ModRes'] = _MODRES
DESCRIPTOR.message_types_by_name['DelParam'] = _DELPARAM
DESCRIPTOR.message_types_by_name['DelRes'] = _DELRES
DESCRIPTOR.message_types_by_name['SelParam'] = _SELPARAM
DESCRIPTOR.message_types_by_name['SelRes'] = _SELRES
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddParam = _reflection.GeneratedProtocolMessageType('AddParam', (_message.Message,), {
  'DESCRIPTOR' : _ADDPARAM,
  '__module__' : 'db_crud_pb2'
  # @@protoc_insertion_point(class_scope:AddParam)
  })
_sym_db.RegisterMessage(AddParam)

AddRes = _reflection.GeneratedProtocolMessageType('AddRes', (_message.Message,), {
  'DESCRIPTOR' : _ADDRES,
  '__module__' : 'db_crud_pb2'
  # @@protoc_insertion_point(class_scope:AddRes)
  })
_sym_db.RegisterMessage(AddRes)

ModParam = _reflection.GeneratedProtocolMessageType('ModParam', (_message.Message,), {
  'DESCRIPTOR' : _MODPARAM,
  '__module__' : 'db_crud_pb2'
  # @@protoc_insertion_point(class_scope:ModParam)
  })
_sym_db.RegisterMessage(ModParam)

ModRes = _reflection.GeneratedProtocolMessageType('ModRes', (_message.Message,), {
  'DESCRIPTOR' : _MODRES,
  '__module__' : 'db_crud_pb2'
  # @@protoc_insertion_point(class_scope:ModRes)
  })
_sym_db.RegisterMessage(ModRes)

DelParam = _reflection.GeneratedProtocolMessageType('DelParam', (_message.Message,), {
  'DESCRIPTOR' : _DELPARAM,
  '__module__' : 'db_crud_pb2'
  # @@protoc_insertion_point(class_scope:DelParam)
  })
_sym_db.RegisterMessage(DelParam)

DelRes = _reflection.GeneratedProtocolMessageType('DelRes', (_message.Message,), {
  'DESCRIPTOR' : _DELRES,
  '__module__' : 'db_crud_pb2'
  # @@protoc_insertion_point(class_scope:DelRes)
  })
_sym_db.RegisterMessage(DelRes)

SelParam = _reflection.GeneratedProtocolMessageType('SelParam', (_message.Message,), {
  'DESCRIPTOR' : _SELPARAM,
  '__module__' : 'db_crud_pb2'
  # @@protoc_insertion_point(class_scope:SelParam)
  })
_sym_db.RegisterMessage(SelParam)

SelRes = _reflection.GeneratedProtocolMessageType('SelRes', (_message.Message,), {
  'DESCRIPTOR' : _SELRES,
  '__module__' : 'db_crud_pb2'
  # @@protoc_insertion_point(class_scope:SelRes)
  })
_sym_db.RegisterMessage(SelRes)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {

  'ResultEntry' : _reflection.GeneratedProtocolMessageType('ResultEntry', (_message.Message,), {
    'DESCRIPTOR' : _RESULT_RESULTENTRY,
    '__module__' : 'db_crud_pb2'
    # @@protoc_insertion_point(class_scope:Result.ResultEntry)
    })
  ,
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'db_crud_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  })
_sym_db.RegisterMessage(Result)
_sym_db.RegisterMessage(Result.ResultEntry)


DESCRIPTOR._options = None
_RESULT_RESULTENTRY._options = None

_DATASERVICE = _descriptor.ServiceDescriptor(
  name='DataService',
  full_name='DataService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=449,
  serialized_end=594,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddData',
    full_name='DataService.AddData',
    index=0,
    containing_service=None,
    input_type=_ADDPARAM,
    output_type=_ADDRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ModData',
    full_name='DataService.ModData',
    index=1,
    containing_service=None,
    input_type=_MODPARAM,
    output_type=_MODRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DelData',
    full_name='DataService.DelData',
    index=2,
    containing_service=None,
    input_type=_DELPARAM,
    output_type=_DELRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SelData',
    full_name='DataService.SelData',
    index=3,
    containing_service=None,
    input_type=_SELPARAM,
    output_type=_SELRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATASERVICE)

DESCRIPTOR.services_by_name['DataService'] = _DATASERVICE

# @@protoc_insertion_point(module_scope)
