[[bin]]
name = "bootstrap"
path = "src/main.rs"

[dependencies]
anyhow = "1"
lazy_static = "1"
log = "0.4"
pretty_env_logger = "0.4"
regex = "1"
serde_json = "1"
thiserror = "1"

[dependencies.deltalake]
features = ["s3"]
path = "../deltalake"
version = "0"

[dependencies.lambda_runtime]
version = "0.3"

[dependencies.openssl]
features = ["vendored"]
version = "0.10"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.tokio]
features = ["fs", "macros", "rt", "io-util"]
version = "1"

[dependencies.tokio-stream]
features = ["fs"]
version = "0"

[dev-dependencies]
rusoto_core = "0.46"
rusoto_credential = "0.46"
rusoto_s3 = "0.46"

[package]
authors = ["xianwill <christianwilliams79@gmail.com>"]
edition = "2018"
name = "lambda-delta-checkpoint"
version = "0.1.0"
