[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    'requests>=2.24.0',
    'python-dateutil>=2.8.1',
    'SQLAlchemy>=1.3.17',
    'records>=0.5.3',
]
build-backend = "setuptools.build_meta"