[tool.poetry]
name = "xiao-asgi"
version = "0.2.1"
description = "A small ASGI framework."
authors = ["Jonathan Staniforth <jonathanstaniforth@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/limber-project/limberframework"
keywords = ["python", "asgi"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pre-commit = "^2.10.0"
coverage = "^5.4"
pytest = "^6.2.2"
pytest-asyncio = "^0.16.0"
tox = "^3.24.4"

[tool.black]
line-length = 79
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
line_length = 79

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
