[tool.poetry]
name = "space-python-sdk"
version = "0.1.0"
description = ""
authors = ["Abbas Jafari <a.jafari@zurich.ch>"]
packages = [
    {include = "space"}
]

[tool.poetry.dependencies]
python = "^3.8"
twine = "^3.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
