kind: ManifestVariable
id: "nmachine.telem.variable.strategy"
flat_key: "strategy"
title: "Storage Strategy"
level: "default_vars"
info: "Where the database lives. Your choice should take into account
your data ownership needs."
default_value: "pvc"
input:
  kind: LargeSelectInput
  options:
    - id: "pvc"
      title: "In-Cluster Managed Database"
      info: "Your NMachine's telemetry database and its related workloads/configs
      live in your cluster, managed by the plugin. Total data ownership."
    - id: "managed_cloud"
      title: "NMachine Cloud"
      info: "Your NMachine's telemetry database lives at api.nmachine.io.
      You can port data across NMachine instances in case
      one goes down, or team members need exact clones."
    - id: "self_managed"
      title: "Bring your own Infrastructure"
      info: "You supply a URL to a MongoDB database, which you are responsible
      for maintaining and securing. A good option for starting out cheaply."
validators:
  - operator: in
    check_against: ["pvc", "self_managed", "managed_cloud"]

---

kind: ManifestVariable
id: "nmachine.telem.variable.mongo.port"
flat_key: "mongo.port"
title: Self-managed Database Port
info: "Only set if using a self-managed database. Port on which
your database is running. Value will be ignored if strategy is PVC."
validators:
  - kind: FormatPredicate
    check_against: integer

---

kind: ManifestVariable
id: "nmachine.telem.variable.mongo.host"
flat_key: "mongo.host"
title: "Self-managed Database Host"
info: "Only set if using a self-managed database. Port on which
your database is running. Value will be ignored if strategy is PVC. For
 formatting information, like
how to include the password, refer to the MongoDB docs."
