#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['ceng']

package_data = \
{'': ['*']}

install_requires = \
['numpy >=1.20', 'scipy >=1.7', 'wrapt >= 1.13', 'numba']

extras_require = \
{'test': ['pytest >=6.2']}

setup(name='ceng',
      version='0.5',
      description='Tool for Coding Tasks Specific to Civil Engineering',
      author=None,
      author_email='Ricky L Teachey Jr <ricky@teachey.org>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.9',
     )
