name: TileDB CLI CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Print python and pip version information for debugging.
    - name: 'Print python version in bash task'
      run: |
        echo '==== Python information ===='
        which python
        which pip
        python --version
        echo '============================'
      shell: bash
      
    - name: 'Print env'
      run: printenv
      shell: bash
      
    - name: 'Install TileDB-CLI'
      run: python -m pip install .[dev,ci]
      shell: bash

    - name: 'Run tests'
      run: |
        pytest -vs
      shell: bash
      env:
        TILEDB_REST_TOKEN: ${{ secrets.TILEDB_REST_TOKEN }}

    - name: 'Print log files (failed build only)'
      run: |
        set -xeo pipefail
        # Display log files if the build failed
        echo 'Dumping log files for failed build'
        echo '----------------------------------'
        for f in $(find $BUILD_REPOSITORY_LOCALPATH/build -name *.log);
          do echo '------'
             echo $f
             echo '======'
             cat $f
          done;
      shell: bash
      if: ${{ failure() }} # only run this job if the build step failed

