name: TileDB CLI Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - # restore after https://github.com/psf/black/issues/2079
        #uses: psf/black@stable
        uses: psf/black@20.8b1
        with:
          args: ". --check"
