# Generated by Django 2.2 on 2021-09-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('CID', models.AutoField(primary_key=True, serialize=False)),
                ('CName', models.CharField(max_length=300)),
                ('Key', models.IntegerField(default=0)),
                ('Status', models.IntegerField(default=0)),
            ],
        ),
    ]
