# Generated by Django 2.2 on 2021-09-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Key',
            field=models.CharField(default='', max_length=300),
        ),
    ]
