# Generated by Django 2.2 on 2021-09-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FModel', '0003_clients_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='LoginStatus',
            field=models.IntegerField(default=0),
        ),
    ]
