# Generated by Django 2.2 on 2021-11-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FModel', '0004_clients_loginstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='ModelType',
            field=models.IntegerField(default=0),
        ),
    ]
