# Generated by Django 2.2 on 2021-11-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FModel', '0005_clients_modeltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='ModelType',
            field=models.IntegerField(default=-1),
        ),
    ]
