[tool.poetry]
name = "ContinuousIntegrationDependency"
version = "1.0.16"
description = ""
authors = ["Aaron Shiels <aaron.shiels@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
