# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DiagnosisIdentificationWithTimestamp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDiagnosisIdentificationWithTimestamp(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DiagnosisIdentificationWithTimestamp()
        x.Init(buf, n + offset)
        return x

    # DiagnosisIdentificationWithTimestamp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DiagnosisIdentificationWithTimestamp
    def DiagnosisIdentification(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from common.log.diagnosis.fbs.DiagnosisIdentification import DiagnosisIdentification
            obj = DiagnosisIdentification()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DiagnosisIdentificationWithTimestamp
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DiagnosisIdentificationWithTimestampStart(builder): builder.StartObject(2)
def DiagnosisIdentificationWithTimestampAddDiagnosisIdentification(builder, diagnosisIdentification): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(diagnosisIdentification), 0)
def DiagnosisIdentificationWithTimestampAddTimestamp(builder, timestamp): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)
def DiagnosisIdentificationWithTimestampEnd(builder): return builder.EndObject()
