# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GetMainDiagnosisText(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGetMainDiagnosisText(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetMainDiagnosisText()
        x.Init(buf, n + offset)
        return x

    # GetMainDiagnosisText
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetMainDiagnosisText
    def MainDiagnosisNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GetMainDiagnosisText
    def Language(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def GetMainDiagnosisTextStart(builder): builder.StartObject(2)
def GetMainDiagnosisTextAddMainDiagnosisNumber(builder, mainDiagnosisNumber): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(mainDiagnosisNumber), 0)
def GetMainDiagnosisTextAddLanguage(builder, language): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(language), 0)
def GetMainDiagnosisTextEnd(builder): return builder.EndObject()
