# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ListDiagnosisIdentificationWithTimestamp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsListDiagnosisIdentificationWithTimestamp(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ListDiagnosisIdentificationWithTimestamp()
        x.Init(buf, n + offset)
        return x

    # ListDiagnosisIdentificationWithTimestamp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ListDiagnosisIdentificationWithTimestamp
    def ListDiagnosisIdentificationWithTimestamp(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from common.log.diagnosis.fbs.DiagnosisIdentificationWithTimestamp import DiagnosisIdentificationWithTimestamp
            obj = DiagnosisIdentificationWithTimestamp()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ListDiagnosisIdentificationWithTimestamp
    def ListDiagnosisIdentificationWithTimestampLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ListDiagnosisIdentificationWithTimestamp
    def ListDiagnosisIdentificationWithTimestampIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ListDiagnosisIdentificationWithTimestampStart(builder): builder.StartObject(1)
def ListDiagnosisIdentificationWithTimestampAddListDiagnosisIdentificationWithTimestamp(builder, listDiagnosisIdentificationWithTimestamp): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(listDiagnosisIdentificationWithTimestamp), 0)
def ListDiagnosisIdentificationWithTimestampStartListDiagnosisIdentificationWithTimestampVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ListDiagnosisIdentificationWithTimestampEnd(builder): return builder.EndObject()
