
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-15T08:57:19-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "965c50f8c5c9c2977cdcfa39da62ed907a6be7ed",
 "version": "2.0.0a18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
