VERSION_YEAR = 2021
VERSION_MONTH = int('11')
VERSION_DAY = int('17')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('11')
MAJOR_VERSION = 1
MINOR_VERSION = 6
PATCH_VERSION = 202111171111
version_date = '2021/11/17 11:11'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
