
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-11T11:47:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6df0fd10e708f7316813dad09906fb8ea158cd15",
 "version": "0.7.1.post.dev154"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
