
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-11T17:56:09+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "fd8edc97beb48856658941e11dbc25289defd3ef",
 "version": "2021.11.0+1.gfd8edc9.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
