[tool.poetry]
name = "click_sources"
version = "0.1.0-alpha1"
description = ""
authors = []
license = "GPLv2"
packages = [
  { include = "click_sources/"}
]
include = [
   "LICENSE"
]

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.0.3"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pre-commit = "^2.15.0"
tox = "^3.24.4"
tox-poetry-installer = "^0.8.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
