# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Cyclic(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCyclic(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Cyclic()
        x.Init(buf, n + offset)
        return x

    # Cyclic
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Cyclic
    def ErrorCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Cyclic
    def Reset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Cyclic
    def ErrorReaction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from common.scheduler.watchdog.fbs.ErrorReaction import ErrorReaction
            obj = ErrorReaction()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def CyclicStart(builder): builder.StartObject(3)
def CyclicAddErrorCount(builder, errorCount): builder.PrependUint32Slot(0, errorCount, 0)
def CyclicAddReset(builder, reset): builder.PrependBoolSlot(1, reset, 0)
def CyclicAddErrorReaction(builder, errorReaction): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(errorReaction), 0)
def CyclicEnd(builder): return builder.EndObject()
