
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-16T11:11:15+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e607264f33fc0e5503f1b7f1f530686f14df9ae2",
 "version": "0.7.1.post.dev158"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
