# Generated by Django 3.2.9 on 2021-11-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_variables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVariableBoolean',
            fields=[
            ],
            options={
                'verbose_name': 'boolean value',
                'verbose_name_plural': 'boolean values',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_site_variables.sitevariable',),
        ),
        migrations.CreateModel(
            name='SiteVariableNumber',
            fields=[
            ],
            options={
                'verbose_name': 'number value',
                'verbose_name_plural': 'number values',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_site_variables.sitevariable',),
        ),
        migrations.CreateModel(
            name='SiteVariableText',
            fields=[
            ],
            options={
                'verbose_name': 'string',
                'verbose_name_plural': 'strings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_site_variables.sitevariable',),
        ),
        migrations.AlterField(
            model_name='sitevariable',
            name='name',
            field=models.SlugField(max_length=128, unique=True, verbose_name='name'),
        ),
    ]
