'''__init__.py'''


from mastapy._internal.dummy_base_class_importer import _DummyBaseClassImport


with _DummyBaseClassImport():
    from ._949 import AddendumModificationDistributionRule
    from ._950 import BacklashSpecification
    from ._951 import BasicRackProfiles
    from ._952 import CaseHardeningProperties
    from ._953 import CreateNewSuitableCutterOption
    from ._954 import CrossedAxisCylindricalGearPair
    from ._955 import CrossedAxisCylindricalGearPairLineContact
    from ._956 import CrossedAxisCylindricalGearPairPointContact
    from ._957 import CylindricalGearAbstractRack
    from ._958 import CylindricalGearAbstractRackFlank
    from ._959 import CylindricalGearBasicRack
    from ._960 import CylindricalGearBasicRackFlank
    from ._961 import CylindricalGearCuttingOptions
    from ._962 import CylindricalGearDefaults
    from ._963 import CylindricalGearDesign
    from ._964 import CylindricalGearDesignConstraint
    from ._965 import CylindricalGearDesignConstraints
    from ._966 import CylindricalGearDesignConstraintsDatabase
    from ._967 import CylindricalGearDesignConstraintSettings
    from ._968 import CylindricalGearDesignSettings
    from ._969 import CylindricalGearFlankDesign
    from ._970 import CylindricalGearMeshDesign
    from ._971 import CylindricalGearMeshFlankDesign
    from ._972 import CylindricalGearMicroGeometrySettings
    from ._973 import CylindricalGearPinionTypeCutter
    from ._974 import CylindricalGearPinionTypeCutterFlank
    from ._975 import CylindricalGearProfileMeasurement
    from ._976 import CylindricalGearProfileMeasurementType
    from ._977 import CylindricalGearProfileModifications
    from ._978 import CylindricalGearSetDesign
    from ._979 import CylindricalGearSetFlankDesign
    from ._980 import CylindricalGearSetMacroGeometryOptimiser
    from ._981 import CylindricalGearSetManufacturingConfigurationSelection
    from ._982 import CylindricalGearTableMGItemDetail
    from ._983 import CylindricalGearTableWithMGCharts
    from ._984 import CylindricalGearToothThicknessSpecification
    from ._985 import CylindricalMeshAngularBacklash
    from ._986 import CylindricalMeshedGear
    from ._987 import CylindricalMeshedGearFlank
    from ._988 import CylindricalMeshLinearBacklashSpecification
    from ._989 import CylindricalPlanetaryGearSetDesign
    from ._990 import CylindricalPlanetGearDesign
    from ._991 import DIN3967AllowanceSeries
    from ._992 import DIN3967ToleranceSeries
    from ._993 import DoubleAxisScaleAndRange
    from ._994 import FinishStockSpecification
    from ._995 import FinishToothThicknessDesignSpecification
    from ._996 import GearFitSystems
    from ._997 import GearManufacturingConfigSetupViewModel
    from ._998 import GearSetFCAImportSetup
    from ._999 import GearSetManufacturingConfigurationSetup
    from ._1000 import GeometrySpecificationType
    from ._1001 import HardenedMaterialProperties
    from ._1002 import HardnessProfileCalculationMethod
    from ._1003 import HeatTreatmentType
    from ._1004 import ISO6336Geometry
    from ._1005 import ISO6336GeometryBase
    from ._1006 import ISO6336GeometryForShapedGears
    from ._1007 import ISO6336GeometryManufactured
    from ._1008 import LinearBacklashSepcification
    from ._1009 import LTCALoadCaseModifiableSettings
    from ._1010 import LtcaSettings
    from ._1011 import MicroGeometryConvention
    from ._1012 import MicroGeometryProfileConvention
    from ._1013 import Micropitting
    from ._1014 import NamedPlanetAssemblyIndex
    from ._1015 import NamedPlanetSideBandAmplitudeFactor
    from ._1016 import ReadonlyToothThicknessSpecification
    from ._1017 import RelativeMeasurementViewModel
    from ._1018 import RelativeValuesSpecification
    from ._1019 import Scuffing
    from ._1020 import ScuffingCoefficientOfFrictionMethods
    from ._1021 import ScuffingTemperatureMethodsAGMA
    from ._1022 import ScuffingTemperatureMethodsISO
    from ._1023 import ShaperEdgeTypes
    from ._1024 import SpurGearLoadSharingCodes
    from ._1025 import StandardRack
    from ._1026 import StandardRackFlank
    from ._1027 import SurfaceRoughness
    from ._1028 import ThicknessType
    from ._1029 import TiffAnalysisSettings
    from ._1030 import TipAlterationCoefficientMethod
    from ._1031 import TolerancedMetalMeasurements
    from ._1032 import TolerancedValueSpecification
    from ._1033 import ToothFlankFractureAnalysisSettings
    from ._1034 import ToothThicknessSpecification
    from ._1035 import ToothThicknessSpecificationBase
    from ._1036 import TypeOfMechanismHousing
    from ._1037 import Usage
