info = {"message": "Bump 1.4rc1", "commit": "4a6094b173d1b18a3e6c0c25011eb65f00848f8a", "date": "2021-11-11 12:46:54 +0000", "branch": "release/1.4", "version": "1.3.0+156.g4a6094b1"}

# This file is automatically generated by version.py
# Do not include it to git!
