# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbtypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# data of a single registered axis transformation
class KinCfgAxsTrafoDataSingle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsKinCfgAxsTrafoDataSingle(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KinCfgAxsTrafoDataSingle()
        x.Init(buf, n + offset)
        return x

    # KinCfgAxsTrafoDataSingle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Name of the axis transformation
    # KinCfgAxsTrafoDataSingle
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Description of the axis transformation
    # KinCfgAxsTrafoDataSingle
    def Description(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Image (link) of the axis transformation
    # KinCfgAxsTrafoDataSingle
    def Image(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Reference to the documentation of the axis transformation
    # KinCfgAxsTrafoDataSingle
    def DocRef(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Version string of the axis transformation
    # KinCfgAxsTrafoDataSingle
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Point of work of the axis transformation
    # KinCfgAxsTrafoDataSingle
    def Pow(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 1

    # All configuration parameters of the axis transformation
    # KinCfgAxsTrafoDataSingle
    def Parameters(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from motion.core.fbtypes.KinCfgAxsTrafoAllParam import KinCfgAxsTrafoAllParam
            obj = KinCfgAxsTrafoAllParam()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def KinCfgAxsTrafoDataSingleStart(builder): builder.StartObject(7)
def KinCfgAxsTrafoDataSingleAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def KinCfgAxsTrafoDataSingleAddDescription(builder, description): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)
def KinCfgAxsTrafoDataSingleAddImage(builder, image): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(image), 0)
def KinCfgAxsTrafoDataSingleAddDocRef(builder, docRef): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(docRef), 0)
def KinCfgAxsTrafoDataSingleAddVersion(builder, version): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(version), 0)
def KinCfgAxsTrafoDataSingleAddPow(builder, pow): builder.PrependInt8Slot(5, pow, 1)
def KinCfgAxsTrafoDataSingleAddParameters(builder, parameters): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(parameters), 0)
def KinCfgAxsTrafoDataSingleEnd(builder): return builder.EndObject()
