# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbtypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# general system configuration
class SysCfg(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSysCfg(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SysCfg()
        x.Init(buf, n + offset)
        return x

    # SysCfg
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # configuration of the product coordinate systems 
    # SysCfg
    def Pcs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from motion.core.fbtypes.SysCfgPcsAll import SysCfgPcsAll
            obj = SysCfgPcsAll()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # system function configuration
    # SysCfg
    def Function(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from motion.core.fbtypes.SysCfgFunction import SysCfgFunction
            obj = SysCfgFunction()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # internal system configuration
    # SysCfg
    def Internal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from motion.core.fbtypes.SysCfgInternal import SysCfgInternal
            obj = SysCfgInternal()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # configuration of the safe and work areas
    # SysCfg
    def SafeAreas(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from motion.core.fbtypes.SysCfgSafeAreaAll import SysCfgSafeAreaAll
            obj = SysCfgSafeAreaAll()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SysCfgStart(builder): builder.StartObject(4)
def SysCfgAddPcs(builder, pcs): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pcs), 0)
def SysCfgAddFunction(builder, function): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(function), 0)
def SysCfgAddInternal(builder, internal): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(internal), 0)
def SysCfgAddSafeAreas(builder, safeAreas): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(safeAreas), 0)
def SysCfgEnd(builder): return builder.EndObject()
