[tool.poetry]
name = "djdt-pev2"
version = "0.2.0"
description = "Django Debug Toolbar Postgress Exlain Visualizer 2 panel"
authors = ["william chu <williamchu@uptickhq.com>"]

[tool.poetry.dependencies]
python = "^3.7"
django-debug-toolbar = "^3.2.0"
sqlparse = "*"

[tool.poetry.dev-dependencies]
dj-database-url = "^0.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

##### Tooling configuraiton
[tool.black]
target-version = ['py38']
line-length = 100
experimental_string_processing = true

[tool.isort]
profile = 'black'
