#数据常量
INDEX = 'index'
DATE = 'date'
SYMBOL = 'symbol'
PRE_CLOSE_PRICE = 'pre_close_price'
CLOSE_PRICE = 'close_price'
OPEN_PRICE = 'open_price'
HIGH_PRICE = 'high_price'
LOW_PRICE = 'low_price'
TURNOVER_RATE = 'turnover_rate'
VOLUME = 'volume'
AMOUNT = 'amount'
TOTAL_MKT_VAL = 'total_market_value'
CIRC_MKT_VAL = 'circulate_market_value'
MEAN_RETURNS = 'return'
WEIGHTS = 'perc'