dependencies = [
    'PyYAML',
    'pycryptodome',
]

[build-system]
requires = [
    "flit_core >=2,<4",
    'setuptools_scm'
]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "secretm"
author = "Bailey Wickham"
author-email = "baileywickham@gmail.com"
home-page = "https://github.com/baileywickham/secrets"
classifiers = [ "License :: OSI Approved :: MIT License",]
description-file = "README.md"

