[tool.poetry]
name = "primapy-tracing"
version = "0.0.1"
description = "Prima tracing instrumentation library"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
isort = "^5.10.0"
pytest = "^6.2.5"
pylint = "^2.11.1"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.pylint."MESSAGES CONTROL"]
persistent = "no"
max-line-length = 120
disable = ["missing-module-docstring", "fixme",]
