
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-10T12:08:13-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "c2c811f3e91742bf7a15c2b59d7362e930c4a1fc",
 "version": "0.15.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
