# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AoeControl(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAoeControl(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AoeControl()
        x.Init(buf, n + offset)
        return x

    # AoeControl
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AoeControl
    def Request(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.ethercat.master.fbs.AoeControlRequest import AoeControlRequest
            obj = AoeControlRequest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AoeControl
    def Response(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.ethercat.master.fbs.AoeControlResponse import AoeControlResponse
            obj = AoeControlResponse()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def AoeControlStart(builder): builder.StartObject(2)
def AoeControlAddRequest(builder, request): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(request), 0)
def AoeControlAddResponse(builder, response): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(response), 0)
def AoeControlEnd(builder): return builder.EndObject()
