# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AoeData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAoeData(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AoeData()
        x.Init(buf, n + offset)
        return x

    # AoeData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AoeData
    def Request(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.ethercat.master.fbs.AoeDataRequest import AoeDataRequest
            obj = AoeDataRequest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AoeData
    def Response(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.ethercat.master.fbs.AoeDataResponse import AoeDataResponse
            obj = AoeDataResponse()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def AoeDataStart(builder): builder.StartObject(2)
def AoeDataAddRequest(builder, request): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(request), 0)
def AoeDataAddResponse(builder, response): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(response), 0)
def AoeDataEnd(builder): return builder.EndObject()
