# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Checksum(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsChecksum(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Checksum()
        x.Init(buf, n + offset)
        return x

    # Checksum
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Checksum
    def Response(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.ethercat.master.fbs.ChecksumResponse import ChecksumResponse
            obj = ChecksumResponse()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ChecksumStart(builder): builder.StartObject(1)
def ChecksumAddResponse(builder, response): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(response), 0)
def ChecksumEnd(builder): return builder.EndObject()
