# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EthercatMailboxInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # EthercatMailboxInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EthercatMailboxInfo
    def SizeIn(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # EthercatMailboxInfo
    def SizeOut(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateEthercatMailboxInfo(builder, sizeIn, sizeOut):
    builder.Prep(4, 8)
    builder.PrependUint32(sizeOut)
    builder.PrependUint32(sizeIn)
    return builder.Offset()
