# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MasterState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMasterState(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MasterState()
        x.Init(buf, n + offset)
        return x

    # MasterState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MasterState
    def Request(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.ethercat.master.fbs.MasterStateRequest import MasterStateRequest
            obj = MasterStateRequest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MasterState
    def Response(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.ethercat.master.fbs.MasterStateResponse import MasterStateResponse
            obj = MasterStateResponse()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def MasterStateStart(builder): builder.StartObject(2)
def MasterStateAddRequest(builder, request): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(request), 0)
def MasterStateAddResponse(builder, response): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(response), 0)
def MasterStateEnd(builder): return builder.EndObject()
