# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ObjectDictionaryList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsObjectDictionaryList(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ObjectDictionaryList()
        x.Init(buf, n + offset)
        return x

    # ObjectDictionaryList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ObjectDictionaryList
    def Request(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.ethercat.master.fbs.ObjectDictionaryListRequest import ObjectDictionaryListRequest
            obj = ObjectDictionaryListRequest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ObjectDictionaryList
    def Response(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.ethercat.master.fbs.ObjectDictionaryListResponse import ObjectDictionaryListResponse
            obj = ObjectDictionaryListResponse()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ObjectDictionaryListStart(builder): builder.StartObject(2)
def ObjectDictionaryListAddRequest(builder, request): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(request), 0)
def ObjectDictionaryListAddResponse(builder, response): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(response), 0)
def ObjectDictionaryListEnd(builder): return builder.EndObject()
