# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ObjectDictionaryListRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsObjectDictionaryListRequest(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ObjectDictionaryListRequest()
        x.Init(buf, n + offset)
        return x

    # ObjectDictionaryListRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ObjectDictionaryListRequest
    def AddressType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ObjectDictionaryListRequest
    def Address(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # ObjectDictionaryListRequest
    def ListType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ObjectDictionaryListRequest
    def MaxElements(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ObjectDictionaryListRequestStart(builder): builder.StartObject(4)
def ObjectDictionaryListRequestAddAddressType(builder, addressType): builder.PrependUint8Slot(0, addressType, 0)
def ObjectDictionaryListRequestAddAddress(builder, address): builder.PrependUint16Slot(1, address, 0)
def ObjectDictionaryListRequestAddListType(builder, listType): builder.PrependUint8Slot(2, listType, 0)
def ObjectDictionaryListRequestAddMaxElements(builder, maxElements): builder.PrependUint32Slot(3, maxElements, 0)
def ObjectDictionaryListRequestEnd(builder): return builder.EndObject()
