# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SlaveRegister(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSlaveRegister(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SlaveRegister()
        x.Init(buf, n + offset)
        return x

    # SlaveRegister
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SlaveRegister
    def Request(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.ethercat.master.fbs.SlaveRegisterRequest import SlaveRegisterRequest
            obj = SlaveRegisterRequest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SlaveRegister
    def Response(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.ethercat.master.fbs.SlaveRegisterResponse import SlaveRegisterResponse
            obj = SlaveRegisterResponse()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SlaveRegisterStart(builder): builder.StartObject(2)
def SlaveRegisterAddRequest(builder, request): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(request), 0)
def SlaveRegisterAddResponse(builder, response): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(response), 0)
def SlaveRegisterEnd(builder): return builder.EndObject()
