# Generated by Django 3.2.9 on 2021-11-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=128, verbose_name='name')),
                ('content', models.TextField(verbose_name='value')),
                ('value_type', models.PositiveSmallIntegerField(choices=[(0, 'Text'), (1, 'Boolean'), (2, 'Number')], default=0, verbose_name='value type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site variable',
                'verbose_name_plural': 'site variables',
            },
        ),
    ]
