# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbtypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class valueMapping(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsvalueMapping(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = valueMapping()
        x.Init(buf, n + offset)
        return x

    # valueMapping
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # valueMapping
    def Mapping(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from comm.axisprofile.fbtypes.mappingEntry import mappingEntry
            obj = mappingEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # valueMapping
    def MappingLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # valueMapping
    def MappingIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def valueMappingStart(builder): builder.StartObject(1)
def valueMappingAddMapping(builder, mapping): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(mapping), 0)
def valueMappingStartMappingVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def valueMappingEnd(builder): return builder.EndObject()
