name: Upload Python Package

on:
  push:
    branches: [master]
jobs:

  publish:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install flit
      run: |
        python -m pip install --upgrade pip
        pip install flit~=3.0
    - name: Build and publish
      run: |
        flit build
        flit publish
      env:
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
