[tool.poetry]
name = "arcane-pubsub"
version = "1.0.2"
description = "Override pubsub client"
readme = "README.md"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = "^3.6"
arcane-firebase = "^0.1.3"
google-cloud-pubsub = "^2.4.2"
typing-extensions = ">=3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.13"]
build-backend = "poetry.masonry.api"
