VERSION_YEAR = 2021
VERSION_MONTH = int('11')
VERSION_DAY = int('10')
VERSION_HOUR = int('17')
VERSION_MINUTE = int('11')
MAJOR_VERSION = 1
MINOR_VERSION = 5
PATCH_VERSION = 202111101711
version_date = '2021/11/10 17:11'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
