[tool.poetry]
name = "py3a"
version = "0.2.2"
description = "Lib for reading and writing 3a format"
authors = ["DomesticMoth"]
license = "GPLv3"
readme = "README.md"
homepage = "https://github.com/DomesticMoth/py3a"
repository = "https://github.com/DomesticMoth/py3a"
classifiers = [
    "Environment :: Console",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)"
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
