name: fibgrid_env
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - netCDF4
  - pyproj
  - numba
  - pip
  - pip:
    - pygeogrids
    - pytest
    - pytest-cov
    - pytest-mpl
    - flake8
