# automatically generated by the FlatBuffers compiler, do not modify

# namespace: framework

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DependencyList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDependencyList(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DependencyList()
        x.Init(buf, n + offset)
        return x

    # DependencyList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DependencyList
    def Dependencies(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from comm.datalayer.framework.Dependency import Dependency
            obj = Dependency()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DependencyList
    def DependenciesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DependencyList
    def DependenciesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def DependencyListStart(builder): builder.StartObject(1)
def DependencyListAddDependencies(builder, dependencies): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(dependencies), 0)
def DependencyListStartDependenciesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def DependencyListEnd(builder): return builder.EndObject()
