# automatically generated by the FlatBuffers compiler, do not modify

# namespace: framework

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InterfaceList_(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInterfaceList_(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InterfaceList_()
        x.Init(buf, n + offset)
        return x

    # InterfaceList_
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InterfaceList_
    def Interfaces(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from comm.datalayer.framework.Interface_ import Interface_
            obj = Interface_()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InterfaceList_
    def InterfacesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InterfaceList_
    def InterfacesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def InterfaceList_Start(builder): builder.StartObject(1)
def InterfaceList_AddInterfaces(builder, interfaces): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(interfaces), 0)
def InterfaceList_StartInterfacesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def InterfaceList_End(builder): return builder.EndObject()
