"""Autogenerated file: DO NOT EDIT!"""
import typing  # noqa: F401
from dazzler.system import Component, Aspect, UNDEFINED  # noqa: F401


class IconPack(Component):
    """
    A pack of font icons to load.
    """
    name = Aspect(required=True, docstring="Name of the pack to include.")
    url = Aspect(required=True, docstring="Url to load.")
    children = Aspect(children=True)
    class_name = Aspect()
    style = Aspect()

    def __init__(
            self,
            name: str,
            url: str,
            children: typing.Optional[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]] = UNDEFINED,  # noqa: E501
            class_name: typing.Optional[str] = UNDEFINED,
            style: typing.Optional[typing.Dict] = UNDEFINED,
            identity: str = None
    ):
        """
        :param name: Name of the pack to include.
        :param url: Url to load.
        :param children:
        :param class_name:
        :param style:
        """
        Component.__init__(self, locals(), identity)
