[tool.poetry]
name = "adacord"
version = "0.1.13"
description = "The cli and sdk for adacord.com"
authors = ["Christian Barra <me@christianbarra.com>", "Alexandre Savio <alexsavio@gmail.com>" ]

license = "MIT"
readme = "README.md"
homepage = "https://www.adacord.com"
repository = "https://github.com/adacord/cli"

classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

include = [
    "LICENSE",
]

packages = [
    { include = "adacord", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.6"
typer = {extras = ["all"], version = "^0.3.2"}
requests = "^2.26.0"
tabulate = "^0.8.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
isort = "^5.9.3"
flake8 = "^3.9.2"
requests-mock = "^1.9.3"
pre-commit = "^2.15.0"
black = "^21.9b0"
pytest-socket = "^0.4.1"

[tool.poetry.scripts]
adacord = "adacord.cli.main:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--disable-socket"
testpaths = [
    "src",
]

[tool.mypy]
python_version = "3.9"

[tool.isort]
profile = "black"
line_length = 79
multi_line_output = "VERTICAL_HANGING_INDENT"
src_paths = [
    "cli",
    "tests"
]
force_grid_wrap = "0"
ensure_newline_before_comments = "True"
include_trailing_comma = "true"
length_sort = "true"
use_parentheses = "true"
force_single_line = "false"
skip_glob = [".venv", "venv"]
known_first_party = [
    "adacord",
]
known_third_party = [
    "typer",
]

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
