# as per https://docs.github.com/en/code-security/supply-chain-security/enabling-and-disabling-version-updates
#
version: 2
updates:
- package-ecosystem: pip
  directory: /
  reviewers:
  - StanczakDominik
  assignees:
  - StanczakDominik
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: /
  reviewers:
  - StanczakDominik
  assignees:
  - StanczakDominik
  schedule:
    interval: daily
