ch: 64
style_dim: 8
n_downsample: 2
n_res: 4
mlp_dim: 256
n_upsample: 2
img_ch: 3
img_h: 256
img_w: 256
n_scale: 3
n_dis: 4
batch_size: 1
gan_type: lsgan
gan_w: 1.0
recon_x_w: 10.0
recon_s_w: 1.0
recon_c_w: 1.0
recon_x_cyc_w: 0.0
max_epochs: 200
epoch_step: 100
lr: 0.0001
load_size: 286
fine_size: 256
optimizer: 'adam'
adam_beta1: 0.5