batch_size: 8
load_size: 128
ch: 64
label_num: 2
ld: 10.0
gan_type: 'wgan-gp'
adv_weight: 1.0
cls_weight: 10.0
rec_weight: 10.0
lr: 0.0002
max_epochs: 100
epoch_step: 100
optimizer: 'adam'
adam_beta1: 0.5
n_critic: 5