# THIS FILE IS GENERATED BY SETUP.PY
# DO NOT MODIFY BY HAND
version = '2.0.1'
git_version = 'b14f15b4751ad33da4747cf21b90da51b2e23c53'
full_version = '2.0.1'
is_release = True

if not is_release:
    version = full_version