name: pudl-test
channels:
  - conda-forge
  - defaults
  - intake
dependencies:
  - geopandas~=0.9.0
  - numba~=0.53
  - pip~=21.2
  - pygeos~=0.10.0
  - python-snappy~=0.6.0
  - sqlite~=3.36
  - tox~=3.24
