"""
    Alvin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import alvin_api_client
from alvin_api_client.model.data_entity_id import DataEntityID
from alvin_api_client.model.query_lineage_parse_result import QueryLineageParseResult
globals()['DataEntityID'] = DataEntityID
globals()['QueryLineageParseResult'] = QueryLineageParseResult
from alvin_api_client.model.body_get_impact_from_validation_payload_api_v2_impact_analysis_post import BodyGetImpactFromValidationPayloadApiV2ImpactAnalysisPost


class TestBodyGetImpactFromValidationPayloadApiV2ImpactAnalysisPost(unittest.TestCase):
    """BodyGetImpactFromValidationPayloadApiV2ImpactAnalysisPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyGetImpactFromValidationPayloadApiV2ImpactAnalysisPost(self):
        """Test BodyGetImpactFromValidationPayloadApiV2ImpactAnalysisPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BodyGetImpactFromValidationPayloadApiV2ImpactAnalysisPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
