
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-13T10:01:12-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ce4c9ebfed89feab7f9a1dc7112c9da2aad53767",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
