import argparse
from typing import Any, Iterator

LOG: Any
DEFAULT_FILE: str

def get_resource(resource_name: str) -> str: ...
def build_makefile(user_file: str, directory: str, project_name: str = ...) -> Iterator[str]: ...
def entry(args: argparse.Namespace) -> int: ...
def add_app_args(parser: argparse.ArgumentParser) -> None: ...
