# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbtypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdOpt_KinSetMCS(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCmdOpt_KinSetMCS(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdOpt_KinSetMCS()
        x.Init(buf, n + offset)
        return x

    # CmdOpt_KinSetMCS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdOpt_KinSetMCS
    def Base(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from script.manager.fbtypes.CmdOpt_Base import CmdOpt_Base
            obj = CmdOpt_Base()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CmdOpt_KinSetMCS
    def SetName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CmdOpt_KinSetMCSStart(builder): builder.StartObject(2)
def CmdOpt_KinSetMCSAddBase(builder, base): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(base), 0)
def CmdOpt_KinSetMCSAddSetName(builder, setName): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(setName), 0)
def CmdOpt_KinSetMCSEnd(builder): return builder.EndObject()
