# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbtypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdOpt_KinBlend(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCmdOpt_KinBlend(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdOpt_KinBlend()
        x.Init(buf, n + offset)
        return x

    # CmdOpt_KinBlend
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdOpt_KinBlend
    def Base(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from script.manager.fbtypes.CmdOpt_Base import CmdOpt_Base
            obj = CmdOpt_Base()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CmdOpt_KinBlend
    def Dist1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CmdOpt_KinBlend
    def Dist2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def CmdOpt_KinBlendStart(builder): builder.StartObject(3)
def CmdOpt_KinBlendAddBase(builder, base): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(base), 0)
def CmdOpt_KinBlendAddDist1(builder, dist1): builder.PrependFloat64Slot(1, dist1, 0.0)
def CmdOpt_KinBlendAddDist2(builder, dist2): builder.PrependFloat64Slot(2, dist2, 0.0)
def CmdOpt_KinBlendEnd(builder): return builder.EndObject()
