# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbtypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class State_CmdState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsState_CmdState(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = State_CmdState()
        x.Init(buf, n + offset)
        return x

    # State_CmdState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # State_CmdState
    def ObjName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # State_CmdState
    def CmdID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def State_CmdStateStart(builder): builder.StartObject(2)
def State_CmdStateAddObjName(builder, objName): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(objName), 0)
def State_CmdStateAddCmdID(builder, cmdID): builder.PrependUint64Slot(1, cmdID, 0)
def State_CmdStateEnd(builder): return builder.EndObject()
