[tool.poetry]
name = "pullapprove"
version = "3.16.0"
description = "PullApprove is a framework for code review assignment, processes, and policies that integrates natively with your git host."
authors = ["Dropseed <python@dropseed.dev>"]
license = "Business Source License"
readme = "README.md"
homepage = "https://www.pullapprove.com/"
documentation = "https://docs.pullapprove.com/"
repository = "https://github.com/dropseed/pullapprove"
keywords = ["pull request", "code review", "reviewer"]

[tool.poetry.scripts]
pullapprove = "pullapprove.cli:cli"

[tool.poetry.dependencies]
python = "^3.8"
wcmatch = "8.2"
cached-property = "^1.5.2"
requests = "^2.25.1"
Jinja2 = "^3.0.1"
dateparser = "^1.0.0"
PyJWT = "^2.1.0"
cryptography = "^3.4.7"
python-box = "^5.3.0"
marshmallow = "^3.12.1"
PyYAML = "^5.4.1"
CacheControl = {version = "^0.12.6", extras = ["filecache"]}
click = "^8.0.1"
prompt-toolkit = "^3.0.20"
keyring = "^23.2.1"
appdirs = "^1.4.4"
cls-client = "^1.4.0"

[tool.poetry.dev-dependencies]
mypy = "^0.910"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
ipython = "^7.25.0"
ipdb = "^0.13.9"
snapshottest = "^0.6.0"
black = "^21.6b0"
lxml = "^4.6.3"
Markdown = "^3.3.4"
types-PyYAML = "^5.4.3"
types-requests = "^2.25.0"
types-dateparser = "^0.1.3"
types-setuptools = "^57.4.0"
isort = "^5.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
warn_unreachable = true
ignore_missing_imports = true
