
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-10T15:26:27-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "12635e16102a465185a2c411605ef9681ac7c323",
 "version": "4.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
