general:                       #|            DEFAULT VALUES
  database:                    #|---------------------------------------
    sqltype: sqlite            #| sqlite, mysql  , mariadb, postgresql
    client:                    #|       , pymysql, pymysql, psycopg2
    user_name:                 #|       , root   , root   , postgres
    password:                  #| <your_password>
    host: localhost            #|
    port: 5432                 #|       , 3306   , 3306   , 5432
    db_name: ExampleDB         #| <some_arbitrary_name>

  operation_settings:
    frequency: once            # once or any number in minutes
    interval: days             # minutes, hours, days, weeks, months
    timeout: 10                # any number in seconds
    enable_logging: false
    asynchronously: true       # run requests in parallel or iterate over the currency-pairs

jobs:
  JobName:
    request_method:            # historic_rates, trades, order_books, tickers
    update_cp: false
    excluded: null             # comma-separated list of exchange names
    exchanges:                 # all or an comma-separated list of exchange names
    currency_pairs:            # all or an comma-separated list of pairs (e.g. eth-btc, btc-usd,..)
    first_currencies: null     # comma-separated list of currencies (e.g. eth, btc,...)
    second_currencies: null


