
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-15T13:27:16-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9bebbc6d9ce3173db9e41a3209c789df4a3c78c4",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
