[tool.poetry]
name = "rubixinsights"
version = "0.0.36"
description = "rubixin-sights"
authors = ["rubix"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7.1,<4"
boto3 = "^1.15.0"
requests = "2.25.1"
PyYAML = "5.3.1"
SQLAlchemy = "1.3.23"
psycopg2-binary = "2.8.6"
pandas = "1.2.0"

google-auth-httplib2 = "0.0.4"
googleapis-common-protos = "1.52.0"
google-auth-oauthlib = "0.4.2"
google-api-core = "1.26.0"
google-api-python-client = "1.12.8"
Jinja2 = "^2.11.0"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"


[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"