[tool.poetry]
name = "python-youtube-async"
version = "1.0.0"
description = "A Python wrapper around for YouTube Data API."
authors = ["ikaroskun <merle.liukun@gmail.com>"]
license = "MIT"
keywords = ["youtube-api", "youtube-v3-api", "youtube-data-api", "youtube-sdk", "async"]
readme = "README.rst"
homepage = "https://github.com/niwla23/python-youtube-async"
repository = "https://github.com/niwla23/python-youtube-async"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Developers",
]

packages = [
    { include = "pyyoutube" },
    { include = "tests", format = "sdist" },
]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.24.0"
requests-oauthlib = "^1.3.0"
isodate = "^0.6.0"
dataclasses-json = "^0.5.3"
aiohttp = "^3.8.0"


[tool.poetry.dev-dependencies]
responses = "^0.12.0"
pytest = "^6.0.2"
pytest-cov = "^2.10.1"
asyncio = "^3.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
