[tool.poetry]
name = "redocker"
version = "0.1.3"
description = "reverse docker image, container and network"
authors = ["junka"]
license = "BSD"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
redocker = 'redocker.redocker:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
