
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-11T11:26:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d08b20c101d574bc171a4980a8c96a330f9ee7b",
 "version": "0.7.1.post.dev150"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
