
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-11T11:18:51-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "08a35c3106ae2029e3abf9a6cf8c332630f8fa46",
 "version": "4.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
