#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['bestlab_platform', 'bestlab_platform.hobo', 'bestlab_platform.tuya']

package_data = \
{'': ['*']}

install_requires = \
['requests']

extras_require = \
{'docs': ['sphinx', 'sphinx-rtd-theme', 'sphinx-autodoc-typehints'],
 'linters': ['flake8',
             'flake8-bugbear',
             'flake8-comprehensions',
             'mypy',
             'types-requests'],
 'utils': ['python-dotenv']}

setup(name='bestlab_platform',
      version='0.2.2',
      description='Packages to access APIs for different platforms',
      author=None,
      author_email='Wei Mu <wmu100@syr.edu>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
