[tool.poetry]
name = "tembo"
version = "0.0.4"
description = ""
authors = ["dtomlinson <dtomlinson@panaetius.co.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.3"
pendulum = "^2.1.2"
Jinja2 = "^3.0.2"
panaetius = "^2.3.2"


[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
prospector = { extras = ["with_bandit", "with_mypy"], version = "^1.5.1" }
pytest-datadir = "^1.3.1"
duty = "^0.7.0"
pyinstaller = "^4.5.1"
coverage = "^6.0.2"
isort = "^5.10.0"
mkdocs = "^1.2.3"
mkdocs-material = "^7.3.6"
mkdocstrings = "^0.16.2"
mkdocs-gen-files = "^0.3.3"
mkdocs-literate-nav = "^0.4.0"
mkdocs-coverage = "^0.2.4"
mkdocs-click = "^0.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
"tembo" = "tembo.cli.cli:main"
