#-*- coding:utf-8 -*-

# __version__ = '0.1.X'
# __maintainer__ = 'Niklas Wulff'
# __contributors__ = 'Fabia Miorelli, Parth Butte'
# __email__ = 'niklas.wulff@dlr.de'
# __birthdate__ = '2019-02-12'
# __status__ = 'prod'  # options are: dev, test, prod

# This config holds all relative paths and filenames for VencoPy

pathRelative:
    plots: ./output/evaluator/
    parseOutput: ./output/dataParser/
    diaryOutput: ./output/tripDiaryBuilder/
    gridOutput: ./output/gridModeler/
    flexOutput: ./output/flexEstimator/
    evalOutput: ./output/evaluator/
    scripts: ./scripts/
    config: ./config/


numberOfHours: 24  # used for discretizing tripDiaries (not tested for other values than 24)

files:
    MiD17:
        enryptedZipFileB1: B1_Standard-DatensatzpaketEncrypted.zip
        enryptedZipFileB2: B2_Regional-DatensatzpaketEncrypted.zip
        tripDataZipFileRaw: CSV/MiD2017_Regional_Wege.csv
        householdsDataRaw: MiD2017_Regional_Haushalte.csv
        personsDataRaw: MiD2017_Regional_Personen.csv
        tripsDataRaw: MiD2017_Regional_Wege.dta
        purposesProcessed: inputProfiles_Purpose  # inputProfiles_Purpose_RUNLABEL_MiD17.csv
        inputDataDriveProfiles: inputProfiles_Drive  # inputProfiles_Drive_RUNLABEL_MiD17.csv
        inputDataPlugProfiles: inputProfiles_Plug  # inputProfiles_Plug_RUNLABEL_MiD17.csv
        output: vencopy
        vencoPyOutput: vencoPyOutput
        flexPlotName: flexProfileComparison
    MiD08:
        householdsDataRaw: MiD2008_PUF_Haushalte.dta
        personDataRaw: MiD2008_PUF_Personen.dta
        tripsDataRaw: MiD2008_PUF_Wege.dta
        tripsProcessedOld: MiD_procCS_caseID-weekday-weight-activity.xlsx
        purposesProcessedOld: MiD_procCS_caseID-weekday-weight-activity.xlsx
        purposesProcessed: inputProfiles_Purpose  # inputProfiles_Purpose_RUNLABEL_MiD08.csv
        inputDataDriveProfiles: inputProfiles_Drive  # inputProfiles_Drive_RUNLABEL_MiD08.csv
        inputDataPlugProfiles: inputProfiles_Plug  # inputProfiles_Plug_RUNLABEL_MiD08.csv
        output: vencopy
        flexPlotName: flexProfileComparison
    KiD:
        tripsDataRaw: KiD2010-Fahrten-Datei-puf.dta
        vehiclesDataRaw: KiD2010-Fahrzeug-Datei-puf.dta
        # tripsDataRaw: KiD2010_merged.dta
        tripsProcessedOld:
        purposesProcessedOld:
        purposesProcessed:
        inputDataDriveProfiles:
        inputDataPlugProfiles:
        vencoPyOutput:
        flexPlotName:
    output: output
    vencoPyOutput: vencoPyOutput
    aggPlotName: mobilityComparison
    flexPlotName: flexProfileComparison

labels:
    runLabel: beta
    technologyLabel: BEV
    outputFileName: vencopy
    strAdd:
