# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"polyprint": "00_core.ipynb",
         "gauss_fit": "00_core.ipynb",
         "calc_velocities": "00_core.ipynb",
         "assign_velocities": "00_core.ipynb",
         "read_potim": "00_core.ipynb",
         "center_particle": "00_core.ipynb",
         "normalize_traj": "00_core.ipynb",
         "read_traj": "00_core.ipynb",
         "make_primitive_cell": "00_core.ipynb",
         "THz": "01_plot_phonons.ipynb",
         "plot_band_set": "01_plot_phonons.ipynb",
         "plot_bands": "01_plot_phonons.ipynb",
         "plot_bands_file": "01_plot_phonons.ipynb",
         "get_dfset_len": "01_plot_phonons.ipynb",
         "show_dc_conv": "01_plot_phonons.ipynb",
         "build_bnd_lst": "01_plot_phonons.ipynb",
         "build_omega": "01_plot_phonons.ipynb",
         "plot_omega": "01_plot_phonons.ipynb",
         "monitor_phonons": "01_plot_phonons.ipynb",
         "run_alamode": "02_alamode.ipynb",
         "gen": "02_alamode.ipynb",
         "make_disp_force": "02_alamode.ipynb"}

modules = ["core.py",
           "plot.py",
           "alamode.py"]

doc_url = "https://jochym.gitlab.io/dxutils/"

git_url = "https://github.com/jochym/dxutils/tree/nbdev/"

def custom_doc_links(name): return None
