[tool.poetry]
name = "iscc-core"
version = "0.1.2"
build = "build.py"
description = "ISCC - Core Algorithms"
authors = ["Titusz <tp@py7.de>"]
license = "BSD 3-clause"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.6.1,<4.0"
cython = { version = "*", optional = true }
blake3 = "*"
xxhash = "*"
more-itertools = "*"
bitarray-hardbyte = "*"
pybase64 = { version = "*", optional = true }
Pillow = "*"
pydantic = "^1.8.2"

[tool.poetry.extras]
turbo = ["cython", "pybase64"]

[tool.poetry.dev-dependencies]
pytest = "*"
black = { version = "*", allow-prereleases = true }
mkdocs-material = "*"
mkdocstrings = "*"
toml = "*"
iscc-samples = "*"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "wheel"]
build-backend = "poetry.core.masonry.api"
