VERSION_YEAR = 2021
VERSION_MONTH = int('11')
VERSION_DAY = int('14')
VERSION_HOUR = int('06')
VERSION_MINUTE = int('33')
MAJOR_VERSION = 1
MINOR_VERSION = 6
PATCH_VERSION = 202111140633
version_date = '2021/11/14 06:33'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
