#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['mido>=1.2.9']

extras_require = \
{'test': ['pytest>=6.2.2']}

entry_points = \
{'console_scripts': ['windsong = windsong:main']}

setup(name='windsong',
      version='0.1.1',
      description='Transform MIDI files into keyboard keys for Genshin Impact instruments.',
      author='Ong Yong Xin',
      author_email='ongyongxin2020+github@gmail.com',
      url='https://github.com/ongyx/windsong',
      py_modules=['windsong'],
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
