[tool.poetry]
name = "pretty-confusion-matrix"
version = "0.1.0"
description = "plot a pretty confusion matrix (like Matlab) in python using seaborn and matplotlib"
repository = "https://github.com/wcipriano/pretty-print-confusion-matrix"
authors = ["Khuyen Tran <khuyentran1476@gmail.com>"]
keywords = ["confusion matrix"]
readme = "README.md"


[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
matplotlib = "^3.5.0"
seaborn = "^0.11.2"
pandas = "^1.3.4"
numpy = "^1.21.4"
sklearn = "^0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
