# Executables or binaries
[exe]
# liftover coordinates across genomes
liftover = "liftOver"
# gatk, installed via conda
gatk = "gatk"
gatk4 = "gatk"
# vdjtools, installed via conda
vdjtools = "vdjtools"
# cnvpytor
cnvpytor = "cnvpytor"

# Interpreters
[lang]
# Bash
bash = "bash"
# python
python = "python"
# R
rscript = "Rscript"

# Path to files/directories
[path]
# Map chain file for liftover
liftover_chain = ""
# Temporary directory
# Assign via config.py
# tmpdir = ""

[ref]
# The reference genome
reffa = ""
# The reference sequence dictionary
refdict = ""

[misc]
# Number of cores used for each job
ncores = 1
