
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-17T11:32:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b87eda781d98328af8b781aecd82b855a2b5d629",
 "version": "1.15.0.post.dev490"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
