[tool.poetry]
name = "dud"
version = "0.1.0"
description = "experimental static site generator in python"
authors = ["Amal Shaji <18011385+amalshaji@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.2"
typer = "^0.4.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
dud = "dud.main:app"