# Install pre-commit hooks via:
# pre-commit install

# yapf = yet another python formatter
repos:
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.28.0
  hooks:
  - id: yapf
    name: yapf
    args: ["-i"]

- repo: local
  hooks:
  - id: version-number
    name: Check version numbers
    entry: python ./.github/check_version.py
    language: system
    files: '^(setup.json)|(aiida_gaussian/__init__.py)'
