"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lcmt_hydroelastic_contact_surface_tri_for_viz(object):
    __slots__ = ["p_WA", "p_WB", "p_WC", "pressure_A", "pressure_B", "pressure_C"]

    __typenames__ = ["double", "double", "double", "double", "double", "double"]

    __dimensions__ = [[3], [3], [3], None, None, None]

    def __init__(self):
        self.p_WA = [ 0.0 for dim0 in range(3) ]
        self.p_WB = [ 0.0 for dim0 in range(3) ]
        self.p_WC = [ 0.0 for dim0 in range(3) ]
        self.pressure_A = 0.0
        self.pressure_B = 0.0
        self.pressure_C = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_hydroelastic_contact_surface_tri_for_viz._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3d', *self.p_WA[:3]))
        buf.write(struct.pack('>3d', *self.p_WB[:3]))
        buf.write(struct.pack('>3d', *self.p_WC[:3]))
        buf.write(struct.pack(">ddd", self.pressure_A, self.pressure_B, self.pressure_C))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_hydroelastic_contact_surface_tri_for_viz._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_hydroelastic_contact_surface_tri_for_viz._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_hydroelastic_contact_surface_tri_for_viz()
        self.p_WA = struct.unpack('>3d', buf.read(24))
        self.p_WB = struct.unpack('>3d', buf.read(24))
        self.p_WC = struct.unpack('>3d', buf.read(24))
        self.pressure_A, self.pressure_B, self.pressure_C = struct.unpack(">ddd", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if lcmt_hydroelastic_contact_surface_tri_for_viz in parents: return 0
        tmphash = (0x5ee0915899cf0071) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_hydroelastic_contact_surface_tri_for_viz._packed_fingerprint is None:
            lcmt_hydroelastic_contact_surface_tri_for_viz._packed_fingerprint = struct.pack(">Q", lcmt_hydroelastic_contact_surface_tri_for_viz._get_hash_recursive([]))
        return lcmt_hydroelastic_contact_surface_tri_for_viz._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_hydroelastic_contact_surface_tri_for_viz._get_packed_fingerprint())[0]

