# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streammachine/api/streams/v1/streams_v1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from streammachine.api.entities.v1 import entities_v1_pb2 as streammachine_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='streammachine/api/streams/v1/streams_v1.proto',
  package='streammachine.api.streams.v1',
  syntax='proto3',
  serialized_options=b'\n\037io.streammachine.api.streams.v1P\001Z@github.com/strmprivacy/api-definitions-go/api/streams/v1;streams',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-streammachine/api/streams/v1/streams_v1.proto\x12\x1cstreammachine.api.streams.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a/streammachine/api/entities/v1/entities_v1.proto\";\n\x12ListStreamsRequest\x12\x12\n\nbilling_id\x18\x01 \x01(\t\x12\x11\n\trecursive\x18\x02 \x01(\x08\"Q\n\x13ListStreamsResponse\x12:\n\x07streams\x18\x01 \x03(\x0b\x32).streammachine.api.entities.v1.StreamTree\"i\n\x13\x44\x65leteStreamRequest\x12:\n\x03ref\x18\x01 \x01(\x0b\x32(.streammachine.api.entities.v1.StreamRefB\x03\xe0\x41\x02\x12\x16\n\trecursive\x18\x02 \x01(\x08\x42\x03\xe0\x41\x02\"\x16\n\x14\x44\x65leteStreamResponse\"Q\n\x13\x43reateStreamRequest\x12:\n\x06stream\x18\x01 \x01(\x0b\x32%.streammachine.api.entities.v1.StreamB\x03\xe0\x41\x02\"M\n\x14\x43reateStreamResponse\x12\x35\n\x06stream\x18\x01 \x01(\x0b\x32%.streammachine.api.entities.v1.Stream\"f\n\x10GetStreamRequest\x12:\n\x03ref\x18\x01 \x01(\x0b\x32(.streammachine.api.entities.v1.StreamRefB\x03\xe0\x41\x02\x12\x16\n\trecursive\x18\x02 \x01(\x08\x42\x03\xe0\x41\x02\"S\n\x11GetStreamResponse\x12>\n\x0bstream_tree\x18\x01 \x01(\x0b\x32).streammachine.api.entities.v1.StreamTree2\xe0\x03\n\x0eStreamsService\x12r\n\x0bListStreams\x12\x30.streammachine.api.streams.v1.ListStreamsRequest\x1a\x31.streammachine.api.streams.v1.ListStreamsResponse\x12l\n\tGetStream\x12..streammachine.api.streams.v1.GetStreamRequest\x1a/.streammachine.api.streams.v1.GetStreamResponse\x12u\n\x0c\x44\x65leteStream\x12\x31.streammachine.api.streams.v1.DeleteStreamRequest\x1a\x32.streammachine.api.streams.v1.DeleteStreamResponse\x12u\n\x0c\x43reateStream\x12\x31.streammachine.api.streams.v1.CreateStreamRequest\x1a\x32.streammachine.api.streams.v1.CreateStreamResponseBe\n\x1fio.streammachine.api.streams.v1P\x01Z@github.com/strmprivacy/api-definitions-go/api/streams/v1;streamsb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_field__behavior__pb2.DESCRIPTOR,streammachine_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2.DESCRIPTOR,])




_LISTSTREAMSREQUEST = _descriptor.Descriptor(
  name='ListStreamsRequest',
  full_name='streammachine.api.streams.v1.ListStreamsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='billing_id', full_name='streammachine.api.streams.v1.ListStreamsRequest.billing_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recursive', full_name='streammachine.api.streams.v1.ListStreamsRequest.recursive', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=220,
)


_LISTSTREAMSRESPONSE = _descriptor.Descriptor(
  name='ListStreamsResponse',
  full_name='streammachine.api.streams.v1.ListStreamsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='streams', full_name='streammachine.api.streams.v1.ListStreamsResponse.streams', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=303,
)


_DELETESTREAMREQUEST = _descriptor.Descriptor(
  name='DeleteStreamRequest',
  full_name='streammachine.api.streams.v1.DeleteStreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref', full_name='streammachine.api.streams.v1.DeleteStreamRequest.ref', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\002', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recursive', full_name='streammachine.api.streams.v1.DeleteStreamRequest.recursive', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\002', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=410,
)


_DELETESTREAMRESPONSE = _descriptor.Descriptor(
  name='DeleteStreamResponse',
  full_name='streammachine.api.streams.v1.DeleteStreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=434,
)


_CREATESTREAMREQUEST = _descriptor.Descriptor(
  name='CreateStreamRequest',
  full_name='streammachine.api.streams.v1.CreateStreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream', full_name='streammachine.api.streams.v1.CreateStreamRequest.stream', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\002', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=436,
  serialized_end=517,
)


_CREATESTREAMRESPONSE = _descriptor.Descriptor(
  name='CreateStreamResponse',
  full_name='streammachine.api.streams.v1.CreateStreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream', full_name='streammachine.api.streams.v1.CreateStreamResponse.stream', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=596,
)


_GETSTREAMREQUEST = _descriptor.Descriptor(
  name='GetStreamRequest',
  full_name='streammachine.api.streams.v1.GetStreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref', full_name='streammachine.api.streams.v1.GetStreamRequest.ref', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\002', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recursive', full_name='streammachine.api.streams.v1.GetStreamRequest.recursive', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\002', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=598,
  serialized_end=700,
)


_GETSTREAMRESPONSE = _descriptor.Descriptor(
  name='GetStreamResponse',
  full_name='streammachine.api.streams.v1.GetStreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_tree', full_name='streammachine.api.streams.v1.GetStreamResponse.stream_tree', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=702,
  serialized_end=785,
)

_LISTSTREAMSRESPONSE.fields_by_name['streams'].message_type = streammachine_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._STREAMTREE
_DELETESTREAMREQUEST.fields_by_name['ref'].message_type = streammachine_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._STREAMREF
_CREATESTREAMREQUEST.fields_by_name['stream'].message_type = streammachine_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._STREAM
_CREATESTREAMRESPONSE.fields_by_name['stream'].message_type = streammachine_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._STREAM
_GETSTREAMREQUEST.fields_by_name['ref'].message_type = streammachine_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._STREAMREF
_GETSTREAMRESPONSE.fields_by_name['stream_tree'].message_type = streammachine_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2._STREAMTREE
DESCRIPTOR.message_types_by_name['ListStreamsRequest'] = _LISTSTREAMSREQUEST
DESCRIPTOR.message_types_by_name['ListStreamsResponse'] = _LISTSTREAMSRESPONSE
DESCRIPTOR.message_types_by_name['DeleteStreamRequest'] = _DELETESTREAMREQUEST
DESCRIPTOR.message_types_by_name['DeleteStreamResponse'] = _DELETESTREAMRESPONSE
DESCRIPTOR.message_types_by_name['CreateStreamRequest'] = _CREATESTREAMREQUEST
DESCRIPTOR.message_types_by_name['CreateStreamResponse'] = _CREATESTREAMRESPONSE
DESCRIPTOR.message_types_by_name['GetStreamRequest'] = _GETSTREAMREQUEST
DESCRIPTOR.message_types_by_name['GetStreamResponse'] = _GETSTREAMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListStreamsRequest = _reflection.GeneratedProtocolMessageType('ListStreamsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTSTREAMSREQUEST,
  '__module__' : 'streammachine.api.streams.v1.streams_v1_pb2'
  # @@protoc_insertion_point(class_scope:streammachine.api.streams.v1.ListStreamsRequest)
  })
_sym_db.RegisterMessage(ListStreamsRequest)

ListStreamsResponse = _reflection.GeneratedProtocolMessageType('ListStreamsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTSTREAMSRESPONSE,
  '__module__' : 'streammachine.api.streams.v1.streams_v1_pb2'
  # @@protoc_insertion_point(class_scope:streammachine.api.streams.v1.ListStreamsResponse)
  })
_sym_db.RegisterMessage(ListStreamsResponse)

DeleteStreamRequest = _reflection.GeneratedProtocolMessageType('DeleteStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETESTREAMREQUEST,
  '__module__' : 'streammachine.api.streams.v1.streams_v1_pb2'
  # @@protoc_insertion_point(class_scope:streammachine.api.streams.v1.DeleteStreamRequest)
  })
_sym_db.RegisterMessage(DeleteStreamRequest)

DeleteStreamResponse = _reflection.GeneratedProtocolMessageType('DeleteStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETESTREAMRESPONSE,
  '__module__' : 'streammachine.api.streams.v1.streams_v1_pb2'
  # @@protoc_insertion_point(class_scope:streammachine.api.streams.v1.DeleteStreamResponse)
  })
_sym_db.RegisterMessage(DeleteStreamResponse)

CreateStreamRequest = _reflection.GeneratedProtocolMessageType('CreateStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATESTREAMREQUEST,
  '__module__' : 'streammachine.api.streams.v1.streams_v1_pb2'
  # @@protoc_insertion_point(class_scope:streammachine.api.streams.v1.CreateStreamRequest)
  })
_sym_db.RegisterMessage(CreateStreamRequest)

CreateStreamResponse = _reflection.GeneratedProtocolMessageType('CreateStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATESTREAMRESPONSE,
  '__module__' : 'streammachine.api.streams.v1.streams_v1_pb2'
  # @@protoc_insertion_point(class_scope:streammachine.api.streams.v1.CreateStreamResponse)
  })
_sym_db.RegisterMessage(CreateStreamResponse)

GetStreamRequest = _reflection.GeneratedProtocolMessageType('GetStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSTREAMREQUEST,
  '__module__' : 'streammachine.api.streams.v1.streams_v1_pb2'
  # @@protoc_insertion_point(class_scope:streammachine.api.streams.v1.GetStreamRequest)
  })
_sym_db.RegisterMessage(GetStreamRequest)

GetStreamResponse = _reflection.GeneratedProtocolMessageType('GetStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSTREAMRESPONSE,
  '__module__' : 'streammachine.api.streams.v1.streams_v1_pb2'
  # @@protoc_insertion_point(class_scope:streammachine.api.streams.v1.GetStreamResponse)
  })
_sym_db.RegisterMessage(GetStreamResponse)


DESCRIPTOR._options = None
_DELETESTREAMREQUEST.fields_by_name['ref']._options = None
_DELETESTREAMREQUEST.fields_by_name['recursive']._options = None
_CREATESTREAMREQUEST.fields_by_name['stream']._options = None
_GETSTREAMREQUEST.fields_by_name['ref']._options = None
_GETSTREAMREQUEST.fields_by_name['recursive']._options = None

_STREAMSSERVICE = _descriptor.ServiceDescriptor(
  name='StreamsService',
  full_name='streammachine.api.streams.v1.StreamsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=788,
  serialized_end=1268,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListStreams',
    full_name='streammachine.api.streams.v1.StreamsService.ListStreams',
    index=0,
    containing_service=None,
    input_type=_LISTSTREAMSREQUEST,
    output_type=_LISTSTREAMSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetStream',
    full_name='streammachine.api.streams.v1.StreamsService.GetStream',
    index=1,
    containing_service=None,
    input_type=_GETSTREAMREQUEST,
    output_type=_GETSTREAMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteStream',
    full_name='streammachine.api.streams.v1.StreamsService.DeleteStream',
    index=2,
    containing_service=None,
    input_type=_DELETESTREAMREQUEST,
    output_type=_DELETESTREAMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateStream',
    full_name='streammachine.api.streams.v1.StreamsService.CreateStream',
    index=3,
    containing_service=None,
    input_type=_CREATESTREAMREQUEST,
    output_type=_CREATESTREAMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STREAMSSERVICE)

DESCRIPTOR.services_by_name['StreamsService'] = _STREAMSSERVICE

# @@protoc_insertion_point(module_scope)
