[tool.black]
exclude = '''
(
    /(
            .git
            .gitlab
            .vscode
            artifacts
            doc
        |   docs
    )/
)
'''
include = '\.pyi?$'
line_length = 100
target-version = ['py39']
