[tool.poetry]
name = "miningpoolhub_py"
version = "1.0.16"
description = "An async Python wrapper for the Mining Pool Hub REST API"
authors = ["CoryKrol <16892390+CoryKrol@users.noreply.github.com>"]
license = "Apache 2"
readme = "README.rst"
homepage = "https://github.com/CoryKrol/miningpoolhub_py"
repository = "https://github.com/CoryKrol/miningpoolhub_py"

include = [
    "LICENSE.md",
]

[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = "^0.19.2"
Sphinx = { version = "^4.2.0", optional = true }
sphinx-rtd-theme = { version = "^1.0.0", optional = true }
sphinxcontrib-napoleon = { version = "^0.7", optional = true }
aiohttp = "^3.7.4"
yarl = "^1.6.3"

[tool.poetry.extras]
docs = ["Sphinx", "sphinx-rtd-theme", "sphinxcontrib-napoleon"]

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^2.9.0"
flake8 = "^4.0.1"
black = "^21.9b0"
pytest-asyncio = "^0.16.0"
radon = "^5.1.0"
yamllint = "^1.26.3"
codespell = "^2.1.0"
safety = "^1.10.3"
mypy = "^0.910"
pre-commit = "^2.15.0"
mutmut = "^2.2.0"
aioresponses = "^0.7.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
