[tool.poetry]
name = "lbpackages"
version = "0.3.1"
description = "Implements classes and functions for stocks model and db client"
authors = ["Lionel Barbagallo"]
packages = [{include = "lbpackages"}]

[tool.poetry.dependencies]
python = "^3.7.1"
SQLAlchemy = "1.4.24"
psycopg2-binary = "^2.9.1"
pandas = "^1.3.4"
requests = "^2.26.0"
plotly = "^5.3.1"
boto3 = "^1.20.3"


[tool.poetry.dev-dependencies]
pylint = "^2.11.1"
black = "^21.9b0"
isort = "^5.9.3"
mypy = "^0.910"
flake8-docstrings = "^1.6.0"
jupyter = "^1.0.0"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
