# https://docs.readthedocs.io/en/latest/config-file/index.html
version: 2

formats:
  - htmlzip
  - epub

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: requirements/docs.txt
sphinx:
  fail_on_warning: true
