# This workflow will install Python dependencies,
# build the HTML documentation using Sphinx and upload it as artifact
name: Sphinx Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-sphinx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Make HTML Documentation
      run: |
        pushd doc
        make html
        popd
    - name: Prepare gh-pages branch with HTML output from Sphinx
      run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages
          git rm -rf docs
          cp -rv doc/_build/html ./docs
          touch docs/.nojekyll
    - name: Update gh-pages branch
      if: github.ref == 'refs/heads/main'
      run: |
          git config --local user.email "sphinx-upload[bot]@users.noreply.github.com"
          git config --local user.name "sphinx-upload[bot]"
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          git add docs
          git commit --allow-empty -m "sphinx documentation for ${git_hash}"
          git push origin gh-pages
