[tool.poetry]
name = "limioptic"
version = "0.1.1"
description = ""
authors = ["Alexander M. Stolz <alexander.stolz@dvs.ag>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
numpy = "^1.21.2"
scipy = "^1.7.1"
PyQt5 = "^5.15.4"
matplotlib = "^3.4.3"
pyqtgraph = "^0.12.3"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
limioptic = 'limioptic.run:main'


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

