[build-system]
requires = [
    "setuptools>=42",
    "versioningit ~= 0.3.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.versioningit.vcs]
method = "git-archive"
match = ["v*"]
describe-subst = "$Format:%(describe:match=v*)$"
default-tag = '0.0.0'

[tool.versioningit.format]
distance = "{version}.post{distance}+{vcs}{rev}"
dirty = "{version}+d{build_date:%Y%m%d}"
distance-dirty = "{version}.post{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.versioningit.write]
file = "src/saccharide/_version.py"
