language: python
python:
  - 3.6
cache: pip
install: travis_retry pip install "virtualenv" tox codecov
script: tox -e $TOX_ENV
env:
  - TOX_ENV=django20-py38
  - TOX_ENV=django20-py37
  - TOX_ENV=django20-py36
  - TOX_ENV=django20-py35
  - TOX_ENV=django30-py38
  - TOX_ENV=django30-py37
  - TOX_ENV=django30-py36
  - TOX_ENV=django30-py35
