[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
extend-exclude = "analytix/__init__.py"
line-length = 79

[tool.isort]
profile = "black"
