# THIS FILE IS GENERATED BY SETUP.PY
# DO NOT MODIFY BY HAND
version = '2.0.0'
git_version = 'a8c034f49970e7837df55ffc35f2e680a36d9ef3'
full_version = '2.0.0'
is_release = True

if not is_release:
    version = full_version