[tool.poetry]
name = "latex-trim"
version = "0.1.3"
description = "Tool that allows you to include sub-selections of PDFs in latex documents."
authors = ["Oliver Rausch <oliverrausch99@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7,<3.11"
matplotlib = "^3.4.3"
pdf2image = "^1.16.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
latex-trim = 'latex_trim.latex_trim:run'


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
