[tool.poetry]
name = "toolip"
version = "0.2"
description = "A collection of python utils for webapps"
authors = ["Anthony Hillairet <ant@satel.ca>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "0.65.1"
loguru = "0.5.3"
pytz = "2021.1"
shortuuid = "1.0.1"
apispec = "5.1.1"
types-pytz = "^2021.3.0"

[tool.poetry.dev-dependencies]
pytest = "6.2.4"
pytest-cov = "2.12.1"
mypy = "0.910"
flake8 = "3.9.2"
flake8-isort = "4.0.0"
requests = "2.26.0"
types-requests="2.25.0"
black = "21.5b2"
mkdocs = "1.2.3"
mkdocs-awesome-pages-plugin = "v2.6.0"
mkdocs-material = "7.3.6"
lazydocs = "0.4.8"
pydocstyle = "^6.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flit.metadata]
module = "toolip"
author = "Anthony Hillairet"
author-email = "ant@satel.ca"
home-page = "https://github.com/SatelCreative/toolip"
classifiers = [ "License :: OSI Approved :: MIT License",]
description-file = "README.md"


[tool.black]
line-length = 99
skip-string-normalization = true

[tool.isort]
profile = "black"
known_third_party = ["fastapi", "pydantic", "starlette"]

[tool.pydocstyle]
convention = "google"
add-ignore = "D106,D104,D205,D415"

[[tool.mypy.overrides]]
module = [
    'shortuuid',
    'apispec'
]
ignore_missing_imports = true
