# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from streammachine.api.event_contracts.v1 import event_contracts_v1_pb2 as streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2


class EventContractsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListEventContracts = channel.unary_unary(
                '/streammachine.api.event_contracts.v1.EventContractsService/ListEventContracts',
                request_serializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.ListEventContractsRequest.SerializeToString,
                response_deserializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.ListEventContractsResponse.FromString,
                )
        self.GetEventContract = channel.unary_unary(
                '/streammachine.api.event_contracts.v1.EventContractsService/GetEventContract',
                request_serializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.GetEventContractRequest.SerializeToString,
                response_deserializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.GetEventContractResponse.FromString,
                )
        self.CreateEventContract = channel.unary_unary(
                '/streammachine.api.event_contracts.v1.EventContractsService/CreateEventContract',
                request_serializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.CreateEventContractRequest.SerializeToString,
                response_deserializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.CreateEventContractResponse.FromString,
                )
        self.UpdateEventContract = channel.unary_unary(
                '/streammachine.api.event_contracts.v1.EventContractsService/UpdateEventContract',
                request_serializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.UpdateEventContractRequest.SerializeToString,
                response_deserializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.UpdateEventContractResponse.FromString,
                )
        self.ValidateMaskedFields = channel.unary_unary(
                '/streammachine.api.event_contracts.v1.EventContractsService/ValidateMaskedFields',
                request_serializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.ValidateMaskedFieldsRequest.SerializeToString,
                response_deserializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.ValidateMaskedFieldsResponse.FromString,
                )


class EventContractsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListEventContracts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEventContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEventContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateMaskedFields(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventContractsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListEventContracts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEventContracts,
                    request_deserializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.ListEventContractsRequest.FromString,
                    response_serializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.ListEventContractsResponse.SerializeToString,
            ),
            'GetEventContract': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventContract,
                    request_deserializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.GetEventContractRequest.FromString,
                    response_serializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.GetEventContractResponse.SerializeToString,
            ),
            'CreateEventContract': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEventContract,
                    request_deserializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.CreateEventContractRequest.FromString,
                    response_serializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.CreateEventContractResponse.SerializeToString,
            ),
            'UpdateEventContract': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEventContract,
                    request_deserializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.UpdateEventContractRequest.FromString,
                    response_serializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.UpdateEventContractResponse.SerializeToString,
            ),
            'ValidateMaskedFields': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateMaskedFields,
                    request_deserializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.ValidateMaskedFieldsRequest.FromString,
                    response_serializer=streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.ValidateMaskedFieldsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streammachine.api.event_contracts.v1.EventContractsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EventContractsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListEventContracts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streammachine.api.event_contracts.v1.EventContractsService/ListEventContracts',
            streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.ListEventContractsRequest.SerializeToString,
            streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.ListEventContractsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEventContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streammachine.api.event_contracts.v1.EventContractsService/GetEventContract',
            streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.GetEventContractRequest.SerializeToString,
            streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.GetEventContractResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateEventContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streammachine.api.event_contracts.v1.EventContractsService/CreateEventContract',
            streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.CreateEventContractRequest.SerializeToString,
            streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.CreateEventContractResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateEventContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streammachine.api.event_contracts.v1.EventContractsService/UpdateEventContract',
            streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.UpdateEventContractRequest.SerializeToString,
            streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.UpdateEventContractResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidateMaskedFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streammachine.api.event_contracts.v1.EventContractsService/ValidateMaskedFields',
            streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.ValidateMaskedFieldsRequest.SerializeToString,
            streammachine_dot_api_dot_event__contracts_dot_v1_dot_event__contracts__v1__pb2.ValidateMaskedFieldsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
