[tool.poetry]
name = "pyfmask"
version = "0.0.0"
description = ""
authors = ["mtralka <mtralka@umd.edu>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
mypy = "^0.910"
notebook = "^6.4.5"
pre-commit = "^2.15.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
