[tool.poetry]
name = "netts"
version = "0.1.0"
description = "Not name squatting, to be released later this week."
authors = ["Iain-S <25081046+Iain-S@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
