plugin: hive_inventory
name: pdns
stages:
  private:
    provider: vagrant
    separate_repository: False
    cidr: 192.168.0.96/27
    memory_size: 4096
    mirrored_disk_size: 10
    number_of_hosts: 1
  staging:
    provider: gcp
    separate_repository: True
    cidr: 192.168.0.0/24
    instance_type: e2-medium
    region: us-central1
    mirrored_disk_size: 20
    repository_instance_type: e2-medium
    subnets:
    - cidr: 192.168.0.0/26
      name: s-hive0
      available_zone: us-central1-a
    - cidr: 192.168.0.64/26
      name: s-hive1
      available_zone: us-central1-a
    - cidr: 192.168.0.128/26
      name: s-hive2
      available_zone: us-central1-a
  production:
    provider: azure
    separate_repository: True
    cidr: 192.168.0.0/24
    instance_type: Standard_D2s_v3
    region: japaneast
    disk_size: 100
    repository_disk_size: 150
    mirrored_disk_size: 20
    repository_instance_type: Standard_D2s_v3
  # production:
  #   provider: gcp
  #   separate_repository: True
  #   cidr: 192.168.0.0/24
  #   instance_type: n1-standard-2
  #   region: asia-northeast2
  #   mirrored_disk_size: 20
  #   repository_instance_type: n1-standard-2
