
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-13T11:40:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a127d233de9bec8f5533d439f7977aaa48b3f0bc",
 "version": "v0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
