
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-16T18:26:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bb1fe1597f6511c56c95a4c1da8a84d85221b269",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
