[tool.poetry]
name = "iot_to_linkml"
version = "0.1.21"
description = "see https://github.com/microbiomedata/IoT_to_linkml"
authors = ["Mark A. Miller <mamillerpa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
click = "*"
google-api-python-client = "^2.30.0"
google-auth-oauthlib = "^0.4.6"
pandas = "^1.3.4"
linkml = "^1.1.12"
linkml-runtime = "^1.1.6"
pyaml = "^21.10.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
becli = "iot_to_linkml.becli:make_iot_yaml"
