
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-17T04:29:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "503d3d9cde12673cf09235c0164355e4ce083666",
 "version": "1.15.0.post.dev485"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
