# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fit_fill.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fit_fill.proto',
  package='fit_fill',
  syntax='proto3',
  serialized_options=b'H\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x66it_fill.proto\x12\x08\x66it_fill\"\t\n\x07Setting\"\x18\n\x06Vector\x12\x0e\n\x06values\x18\x01 \x03(\x01\"+\n\x06Matrix\x12!\n\x07vectors\x18\x01 \x03(\x0b\x32\x10.fit_fill.Vector\"\x19\n\x07Indices\x12\x0e\n\x06values\x18\x01 \x03(\x05\"*\n\x06Points\x12 \n\x06points\x18\x01 \x03(\x0b\x32\x10.fit_fill.Vector\")\n\x05\x46\x61\x63\x65s\x12 \n\x05\x66\x61\x63\x65s\x18\x01 \x03(\x0b\x32\x11.fit_fill.Indices\")\n\x04Mesh\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bserver_path\x18\x02 \x01(\t\"=\n\x08MeshInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tpoint_num\x18\x02 \x01(\x05\x12\x10\n\x08\x66\x61\x63\x65_num\x18\x03 \x01(\x05\" \n\x08Simulate\x12\x14\n\x0c\x63\x61pture_path\x18\x01 \x01(\t\"2\n\x0eSimulateResult\x12 \n\x06matrix\x18\x01 \x01(\x0b\x32\x10.fit_fill.Matrix2\xa9\x01\n\x07\x46itFill\x12\x31\n\tnew_stage\x12\x11.fit_fill.Setting\x1a\x11.fit_fill.Setting\x12\x31\n\x0bimport_mesh\x12\x0e.fit_fill.Mesh\x1a\x12.fit_fill.MeshInfo\x12\x38\n\x08simulate\x12\x12.fit_fill.Simulate\x1a\x18.fit_fill.SimulateResultB\x02H\x01\x62\x06proto3'
)




_SETTING = _descriptor.Descriptor(
  name='Setting',
  full_name='fit_fill.Setting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=37,
)


_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='fit_fill.Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='fit_fill.Vector.values', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=63,
)


_MATRIX = _descriptor.Descriptor(
  name='Matrix',
  full_name='fit_fill.Matrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vectors', full_name='fit_fill.Matrix.vectors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=108,
)


_INDICES = _descriptor.Descriptor(
  name='Indices',
  full_name='fit_fill.Indices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='fit_fill.Indices.values', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=135,
)


_POINTS = _descriptor.Descriptor(
  name='Points',
  full_name='fit_fill.Points',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='fit_fill.Points.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=179,
)


_FACES = _descriptor.Descriptor(
  name='Faces',
  full_name='fit_fill.Faces',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='faces', full_name='fit_fill.Faces.faces', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=222,
)


_MESH = _descriptor.Descriptor(
  name='Mesh',
  full_name='fit_fill.Mesh',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='fit_fill.Mesh.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_path', full_name='fit_fill.Mesh.server_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=265,
)


_MESHINFO = _descriptor.Descriptor(
  name='MeshInfo',
  full_name='fit_fill.MeshInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='fit_fill.MeshInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='point_num', full_name='fit_fill.MeshInfo.point_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='face_num', full_name='fit_fill.MeshInfo.face_num', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=328,
)


_SIMULATE = _descriptor.Descriptor(
  name='Simulate',
  full_name='fit_fill.Simulate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='capture_path', full_name='fit_fill.Simulate.capture_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=362,
)


_SIMULATERESULT = _descriptor.Descriptor(
  name='SimulateResult',
  full_name='fit_fill.SimulateResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='matrix', full_name='fit_fill.SimulateResult.matrix', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=414,
)

_MATRIX.fields_by_name['vectors'].message_type = _VECTOR
_POINTS.fields_by_name['points'].message_type = _VECTOR
_FACES.fields_by_name['faces'].message_type = _INDICES
_SIMULATERESULT.fields_by_name['matrix'].message_type = _MATRIX
DESCRIPTOR.message_types_by_name['Setting'] = _SETTING
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
DESCRIPTOR.message_types_by_name['Matrix'] = _MATRIX
DESCRIPTOR.message_types_by_name['Indices'] = _INDICES
DESCRIPTOR.message_types_by_name['Points'] = _POINTS
DESCRIPTOR.message_types_by_name['Faces'] = _FACES
DESCRIPTOR.message_types_by_name['Mesh'] = _MESH
DESCRIPTOR.message_types_by_name['MeshInfo'] = _MESHINFO
DESCRIPTOR.message_types_by_name['Simulate'] = _SIMULATE
DESCRIPTOR.message_types_by_name['SimulateResult'] = _SIMULATERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Setting = _reflection.GeneratedProtocolMessageType('Setting', (_message.Message,), {
  'DESCRIPTOR' : _SETTING,
  '__module__' : 'fit_fill_pb2'
  # @@protoc_insertion_point(class_scope:fit_fill.Setting)
  })
_sym_db.RegisterMessage(Setting)

Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR,
  '__module__' : 'fit_fill_pb2'
  # @@protoc_insertion_point(class_scope:fit_fill.Vector)
  })
_sym_db.RegisterMessage(Vector)

Matrix = _reflection.GeneratedProtocolMessageType('Matrix', (_message.Message,), {
  'DESCRIPTOR' : _MATRIX,
  '__module__' : 'fit_fill_pb2'
  # @@protoc_insertion_point(class_scope:fit_fill.Matrix)
  })
_sym_db.RegisterMessage(Matrix)

Indices = _reflection.GeneratedProtocolMessageType('Indices', (_message.Message,), {
  'DESCRIPTOR' : _INDICES,
  '__module__' : 'fit_fill_pb2'
  # @@protoc_insertion_point(class_scope:fit_fill.Indices)
  })
_sym_db.RegisterMessage(Indices)

Points = _reflection.GeneratedProtocolMessageType('Points', (_message.Message,), {
  'DESCRIPTOR' : _POINTS,
  '__module__' : 'fit_fill_pb2'
  # @@protoc_insertion_point(class_scope:fit_fill.Points)
  })
_sym_db.RegisterMessage(Points)

Faces = _reflection.GeneratedProtocolMessageType('Faces', (_message.Message,), {
  'DESCRIPTOR' : _FACES,
  '__module__' : 'fit_fill_pb2'
  # @@protoc_insertion_point(class_scope:fit_fill.Faces)
  })
_sym_db.RegisterMessage(Faces)

Mesh = _reflection.GeneratedProtocolMessageType('Mesh', (_message.Message,), {
  'DESCRIPTOR' : _MESH,
  '__module__' : 'fit_fill_pb2'
  # @@protoc_insertion_point(class_scope:fit_fill.Mesh)
  })
_sym_db.RegisterMessage(Mesh)

MeshInfo = _reflection.GeneratedProtocolMessageType('MeshInfo', (_message.Message,), {
  'DESCRIPTOR' : _MESHINFO,
  '__module__' : 'fit_fill_pb2'
  # @@protoc_insertion_point(class_scope:fit_fill.MeshInfo)
  })
_sym_db.RegisterMessage(MeshInfo)

Simulate = _reflection.GeneratedProtocolMessageType('Simulate', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATE,
  '__module__' : 'fit_fill_pb2'
  # @@protoc_insertion_point(class_scope:fit_fill.Simulate)
  })
_sym_db.RegisterMessage(Simulate)

SimulateResult = _reflection.GeneratedProtocolMessageType('SimulateResult', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATERESULT,
  '__module__' : 'fit_fill_pb2'
  # @@protoc_insertion_point(class_scope:fit_fill.SimulateResult)
  })
_sym_db.RegisterMessage(SimulateResult)


DESCRIPTOR._options = None

_FITFILL = _descriptor.ServiceDescriptor(
  name='FitFill',
  full_name='fit_fill.FitFill',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=417,
  serialized_end=586,
  methods=[
  _descriptor.MethodDescriptor(
    name='new_stage',
    full_name='fit_fill.FitFill.new_stage',
    index=0,
    containing_service=None,
    input_type=_SETTING,
    output_type=_SETTING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='import_mesh',
    full_name='fit_fill.FitFill.import_mesh',
    index=1,
    containing_service=None,
    input_type=_MESH,
    output_type=_MESHINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='simulate',
    full_name='fit_fill.FitFill.simulate',
    index=2,
    containing_service=None,
    input_type=_SIMULATE,
    output_type=_SIMULATERESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FITFILL)

DESCRIPTOR.services_by_name['FitFill'] = _FITFILL

# @@protoc_insertion_point(module_scope)
