[tool.poetry]
name = "nonebot-bison"
version = "0.4.0"
description = "Subscribe message from social medias"
authors = ["felinae98 <felinae225@qq.com>"]
license = "MIT"
homepage = "https://github.com/felinae98/nonebot-bison"
keywords = ["nonebot", "nonebot2", "qqbot"]
readme = "README.md"
packages = [
    { include = "nonebot_bison/*.py", from = "./src/plugins/" },
    { include = "nonebot_bison/platform/*.py", from = "./src/plugins/" }
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython"
]

[tool.poetry.dependencies]
python = "^3.9"
nonebot2 = "^2.0.0-alpha.15"
httpx = ">=0.16.1 <1.0.0"
bs4 = "^0.0.1"
tinydb = "^4.3.0"
feedparser = "^6.0.2"
pyppeteer = "^0.2.5"
pillow = "^8.1.0"
nonebot-adapter-cqhttp = "^2.0.0-alpha.15"
apscheduler = "^3.7.0"

[tool.poetry.dev-dependencies]
ipdb = "^0.13.4"
pytest = "^6.2.4"
pytest-asyncio = "^0.15.1"
respx = "^0.19.0"
coverage = "^5.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.pytest.ini_options]
markers = [
    "compare: compare fetching result with rsshub",
    "render: render img by chrome"
]
