
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-16T10:19:45+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c1fc00b5f993f5098c0520647a0e402d7ed18946",
 "version": "v3.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
