[tool.poetry]
name = "caliph"
version = "0.2.1"
description = "A simple tool to calibrate and convert pH measurements using a two point method."
authors = ["Peter Dunne <peter.dunne@applied-magnetism.com>"]

[tool.poetry.dependencies]
python = "^3.8, <3.11"
numpy = "^1.18"
fire = "^0.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^4.0.1"
black = {version = "^21.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
calibrate-ph = "caliph:calib"
convert-ph = "caliph:conv"

