[tool.poetry]
name = "alina_api"
version = "0.1.0"
description = "irena1.intercity.pl API for intercity employees."
authors = ["Konrad Nowara"]
license = "MIT License"

packages = [
    { include="alina", from="."}
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"