[tool.poetry]
name = "py3a"
version = "0.2.0"
description = "Lib for reading and writing 3a format"
authors = ["DomesticMoth"]
license = "License :: OSI Approved :: GNU General Public License v3 (GPLv3)"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
