[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ['py38']
include = '.pyi?$'
exclude = '''
(
  /(
      .eggs
    | .git
    | .gitlab
    | .hg
    | .mypy_cache
    | .test_cache
    | .tox
    | .venv
  )/
)
'''
